import { db } from "./index";
import { serviceType } from "./schema/services";

// GCMC Service Types
const gcmcServices = [
  // Training Services
  {
    business: "GCMC" as const,
    name: "Human Resource Management Training",
    description:
      "Comprehensive HR management course covering recruitment, performance management, and employee relations",
    category: "TRAINING" as const,
    defaultChecklistItems: [
      "Confirm participant list",
      "Prepare training materials",
      "Set up venue/virtual room",
      "Conduct training session",
      "Collect feedback forms",
      "Issue certificates",
    ],
    estimatedDays: 3,
    defaultFee: "50000.00",
    sortOrder: 1,
  },
  {
    business: "GCMC" as const,
    name: "Customer Relations Training",
    description:
      "Customer service excellence and client relationship management",
    category: "TRAINING" as const,
    defaultChecklistItems: [
      "Confirm participant list",
      "Prepare training materials",
      "Set up venue/virtual room",
      "Conduct training session",
      "Collect feedback forms",
      "Issue certificates",
    ],
    estimatedDays: 2,
    defaultFee: "35000.00",
    sortOrder: 2,
  },
  {
    business: "GCMC" as const,
    name: "Co-operatives and Credit Unions Training",
    description:
      "Training for cooperative and credit union management and governance",
    category: "TRAINING" as const,
    defaultChecklistItems: [
      "Confirm participant list",
      "Prepare training materials",
      "Set up venue/virtual room",
      "Conduct training session",
      "Collect feedback forms",
      "Issue certificates",
    ],
    estimatedDays: 3,
    defaultFee: "45000.00",
    sortOrder: 3,
  },
  {
    business: "GCMC" as const,
    name: "Organisational Management Workshop",
    description: "Leadership and organizational development workshop",
    category: "TRAINING" as const,
    defaultChecklistItems: [
      "Confirm participant list",
      "Prepare training materials",
      "Set up venue/virtual room",
      "Conduct training session",
      "Collect feedback forms",
      "Issue certificates",
    ],
    estimatedDays: 2,
    defaultFee: "40000.00",
    sortOrder: 4,
  },

  // Business Consulting
  {
    business: "GCMC" as const,
    name: "Small Business Development Consultancy",
    description: "Advisory services for small business startup and growth",
    category: "CONSULTING" as const,
    defaultChecklistItems: [
      "Initial consultation meeting",
      "Business assessment",
      "Develop recommendations",
      "Present findings to client",
      "Follow-up support session",
    ],
    estimatedDays: 14,
    defaultFee: "75000.00",
    sortOrder: 5,
  },
  {
    business: "GCMC" as const,
    name: "Business Proposal Preparation",
    description: "Professional business proposal and plan development",
    category: "CONSULTING" as const,
    defaultChecklistItems: [
      "Client briefing",
      "Market research",
      "Draft proposal",
      "Client review",
      "Final revisions",
      "Deliver final document",
    ],
    estimatedDays: 7,
    defaultFee: "45000.00",
    sortOrder: 6,
  },
  {
    business: "GCMC" as const,
    name: "Investment Advisory",
    description: "Investment guidance and opportunity assessment",
    category: "CONSULTING" as const,
    defaultChecklistItems: [
      "Initial assessment",
      "Market analysis",
      "Risk evaluation",
      "Prepare advisory report",
      "Client presentation",
    ],
    estimatedDays: 10,
    defaultFee: "60000.00",
    sortOrder: 7,
  },

  // Company Formation & Registration
  {
    business: "GCMC" as const,
    name: "Company Incorporation",
    description:
      "Full incorporation service including Articles of Incorporation",
    category: "REGISTRATION" as const,
    defaultChecklistItems: [
      "Collect client information",
      "Name search and reservation",
      "Prepare incorporation documents",
      "Client signatures",
      "Submit to Deeds Registry",
      "Obtain Certificate of Incorporation",
      "Deliver documents to client",
    ],
    estimatedDays: 14,
    defaultFee: "85000.00",
    sortOrder: 8,
  },
  {
    business: "GCMC" as const,
    name: "Business Name Registration",
    description: "Registration of business names with the Registrar",
    category: "REGISTRATION" as const,
    defaultChecklistItems: [
      "Collect client information",
      "Name availability search",
      "Prepare registration forms",
      "Client signatures",
      "Submit registration",
      "Obtain Business Registration",
      "Deliver certificate to client",
    ],
    estimatedDays: 7,
    defaultFee: "25000.00",
    sortOrder: 9,
  },
  {
    business: "GCMC" as const,
    name: "Partnership Agreement",
    description: "Drafting and registration of partnership agreements",
    category: "REGISTRATION" as const,
    defaultChecklistItems: [
      "Client consultation",
      "Draft partnership agreement",
      "Review with all partners",
      "Final signatures",
      "File with authorities",
      "Deliver executed copy",
    ],
    estimatedDays: 10,
    defaultFee: "45000.00",
    sortOrder: 10,
  },

  // Paralegal Services
  {
    business: "GCMC" as const,
    name: "Affidavit Preparation",
    description: "Drafting and notarization of affidavits",
    category: "PARALEGAL" as const,
    defaultChecklistItems: [
      "Collect client information",
      "Draft affidavit",
      "Client review",
      "Schedule notarization",
      "Execute affidavit",
      "Deliver to client",
    ],
    estimatedDays: 3,
    defaultFee: "15000.00",
    sortOrder: 11,
  },
  {
    business: "GCMC" as const,
    name: "Agreement of Sale/Purchase",
    description: "Preparation of property sale and purchase agreements",
    category: "PARALEGAL" as const,
    defaultChecklistItems: [
      "Collect property details",
      "Verify ownership documents",
      "Draft agreement",
      "Review with both parties",
      "Schedule execution",
      "Execute and deliver",
    ],
    estimatedDays: 7,
    defaultFee: "35000.00",
    sortOrder: 12,
  },
  {
    business: "GCMC" as const,
    name: "Will Drafting",
    description: "Preparation of last will and testament",
    category: "PARALEGAL" as const,
    defaultChecklistItems: [
      "Client consultation",
      "Gather asset information",
      "Draft will",
      "Client review and revisions",
      "Arrange witnesses",
      "Execute will",
      "Provide secure storage advice",
    ],
    estimatedDays: 7,
    defaultFee: "40000.00",
    sortOrder: 13,
  },
  {
    business: "GCMC" as const,
    name: "Settlement Agreement",
    description: "Preparation of settlement agreements for disputes",
    category: "PARALEGAL" as const,
    defaultChecklistItems: [
      "Understand dispute details",
      "Draft settlement terms",
      "Review with all parties",
      "Revisions as needed",
      "Execute agreement",
      "Distribute copies",
    ],
    estimatedDays: 5,
    defaultFee: "30000.00",
    sortOrder: 14,
  },
  {
    business: "GCMC" as const,
    name: "Separation Agreement",
    description: "Marital separation agreement preparation",
    category: "PARALEGAL" as const,
    defaultChecklistItems: [
      "Client consultation",
      "Gather asset/liability information",
      "Draft separation terms",
      "Review with both parties",
      "Execute agreement",
      "File if required",
    ],
    estimatedDays: 10,
    defaultFee: "45000.00",
    sortOrder: 15,
  },
  {
    business: "GCMC" as const,
    name: "Investment & Partnership Agreement",
    description: "Preparation of investment and partnership documents",
    category: "PARALEGAL" as const,
    defaultChecklistItems: [
      "Client consultation",
      "Define investment terms",
      "Draft agreement",
      "Review with all parties",
      "Execute agreement",
      "Deliver copies",
    ],
    estimatedDays: 7,
    defaultFee: "50000.00",
    sortOrder: 16,
  },

  // Immigration Services
  {
    business: "GCMC" as const,
    name: "Work Permit Application",
    description: "Complete work permit application service",
    category: "IMMIGRATION" as const,
    defaultChecklistItems: [
      "Collect applicant documents",
      "Verify passport validity",
      "Obtain employer sponsorship letter",
      "Complete application forms",
      "Gather supporting documents",
      "Submit application",
      "Track application status",
      "Collect permit when approved",
      "Deliver to client",
    ],
    estimatedDays: 30,
    defaultFee: "75000.00",
    sortOrder: 17,
  },
  {
    business: "GCMC" as const,
    name: "Citizenship Application",
    description: "Citizenship by registration or naturalization",
    category: "IMMIGRATION" as const,
    defaultChecklistItems: [
      "Eligibility assessment",
      "Collect required documents",
      "Complete application forms",
      "Police clearance",
      "Character references",
      "Submit application",
      "Track status",
      "Attend interview if required",
      "Collect certificate",
    ],
    estimatedDays: 90,
    defaultFee: "100000.00",
    sortOrder: 18,
  },
  {
    business: "GCMC" as const,
    name: "Business Visa Assistance",
    description: "Assistance with business visa applications",
    category: "IMMIGRATION" as const,
    defaultChecklistItems: [
      "Determine visa requirements",
      "Collect documents",
      "Complete application",
      "Submit to embassy/consulate",
      "Track status",
      "Advise on interview prep",
    ],
    estimatedDays: 21,
    defaultFee: "45000.00",
    sortOrder: 19,
  },
];

// KAJ Service Types
const kajServices = [
  // Tax & Accounting
  {
    business: "KAJ" as const,
    name: "Personal Income Tax Return",
    description: "Preparation and filing of personal income tax returns",
    category: "TAX" as const,
    defaultChecklistItems: [
      "Collect income documents",
      "Gather deduction receipts",
      "Calculate taxable income",
      "Prepare tax return",
      "Client review and approval",
      "File with GRA",
      "Obtain acknowledgment",
      "Deliver copy to client",
    ],
    estimatedDays: 7,
    defaultFee: "25000.00",
    sortOrder: 1,
  },
  {
    business: "KAJ" as const,
    name: "Corporate Income Tax Return",
    description: "Preparation and filing of corporate tax returns",
    category: "TAX" as const,
    defaultChecklistItems: [
      "Collect financial statements",
      "Review accounting records",
      "Calculate corporate tax",
      "Prepare tax return",
      "Management review and approval",
      "File with GRA",
      "Obtain acknowledgment",
      "Deliver copy to client",
    ],
    estimatedDays: 14,
    defaultFee: "65000.00",
    sortOrder: 2,
  },
  {
    business: "KAJ" as const,
    name: "PAYE Return Preparation",
    description: "Monthly PAYE return preparation and filing",
    category: "TAX" as const,
    defaultChecklistItems: [
      "Collect payroll data",
      "Calculate PAYE deductions",
      "Prepare PAYE schedule",
      "Review calculations",
      "File with GRA",
      "Confirm payment",
      "Provide receipt to client",
    ],
    estimatedDays: 3,
    defaultFee: "15000.00",
    sortOrder: 3,
  },
  {
    business: "KAJ" as const,
    name: "Certificate of Assessment",
    description: "Obtain tax certificate of assessment from GRA",
    category: "TAX" as const,
    defaultChecklistItems: [
      "Verify tax compliance",
      "Prepare application",
      "Submit to GRA",
      "Follow up on processing",
      "Collect certificate",
      "Deliver to client",
    ],
    estimatedDays: 14,
    defaultFee: "20000.00",
    sortOrder: 4,
  },
  {
    business: "KAJ" as const,
    name: "VAT Registration & Returns",
    description: "VAT registration and periodic return filing",
    category: "TAX" as const,
    defaultChecklistItems: [
      "Assess VAT requirements",
      "Prepare registration application",
      "Submit registration",
      "Set up VAT records",
      "Prepare VAT return",
      "File return",
      "Confirm submission",
    ],
    estimatedDays: 7,
    defaultFee: "35000.00",
    sortOrder: 5,
  },

  // Financial Services
  {
    business: "KAJ" as const,
    name: "Financial Statement Preparation",
    description:
      "Preparation of income/expenditure statements and balance sheets",
    category: "ACCOUNTING" as const,
    defaultChecklistItems: [
      "Collect source documents",
      "Review transactions",
      "Prepare trial balance",
      "Draft financial statements",
      "Review with management",
      "Finalize statements",
      "Deliver to client",
    ],
    estimatedDays: 10,
    defaultFee: "45000.00",
    sortOrder: 6,
  },
  {
    business: "KAJ" as const,
    name: "Cash Flow Projection",
    description: "Cash flow forecasting and analysis",
    category: "ACCOUNTING" as const,
    defaultChecklistItems: [
      "Gather historical data",
      "Analyze cash patterns",
      "Prepare projection model",
      "Review assumptions",
      "Present to client",
      "Deliver final report",
    ],
    estimatedDays: 5,
    defaultFee: "30000.00",
    sortOrder: 7,
  },
  {
    business: "KAJ" as const,
    name: "Bank Account Setup Assistance",
    description: "Assistance with business bank account opening",
    category: "ACCOUNTING" as const,
    defaultChecklistItems: [
      "Review bank requirements",
      "Prepare required documents",
      "Complete application forms",
      "Accompany client to bank",
      "Follow up on account opening",
    ],
    estimatedDays: 7,
    defaultFee: "20000.00",
    sortOrder: 8,
  },
  {
    business: "KAJ" as const,
    name: "Loan Application Support",
    description: "Preparation of loan applications and supporting documents",
    category: "ACCOUNTING" as const,
    defaultChecklistItems: [
      "Review loan requirements",
      "Prepare financial projections",
      "Complete loan application",
      "Compile supporting documents",
      "Submit application",
      "Follow up with lender",
    ],
    estimatedDays: 14,
    defaultFee: "40000.00",
    sortOrder: 9,
  },

  // Audit Services
  {
    business: "KAJ" as const,
    name: "NGO Audit",
    description: "Statutory audit for non-governmental organizations",
    category: "AUDIT" as const,
    defaultChecklistItems: [
      "Engagement planning",
      "Risk assessment",
      "Document collection",
      "Audit testing",
      "Review findings",
      "Draft audit report",
      "Management response",
      "Final audit report",
      "Present to board",
    ],
    estimatedDays: 21,
    defaultFee: "150000.00",
    sortOrder: 10,
  },
  {
    business: "KAJ" as const,
    name: "Co-operative Society Audit",
    description: "Statutory audit for cooperative societies",
    category: "AUDIT" as const,
    defaultChecklistItems: [
      "Engagement planning",
      "Review cooperative records",
      "Member verification",
      "Financial audit testing",
      "Governance review",
      "Draft audit report",
      "Management response",
      "Final audit report",
      "Present to members",
    ],
    estimatedDays: 21,
    defaultFee: "120000.00",
    sortOrder: 11,
  },

  // NIS Services
  {
    business: "KAJ" as const,
    name: "NIS Registration",
    description: "Employer and employee NIS registration",
    category: "NIS" as const,
    defaultChecklistItems: [
      "Collect required documents",
      "Complete registration forms",
      "Submit to NIS",
      "Follow up on registration",
      "Obtain NIS numbers",
      "Deliver to client",
    ],
    estimatedDays: 7,
    defaultFee: "15000.00",
    sortOrder: 12,
  },
  {
    business: "KAJ" as const,
    name: "NIS Contribution Schedule",
    description: "Preparation of monthly NIS contribution schedules",
    category: "NIS" as const,
    defaultChecklistItems: [
      "Collect payroll data",
      "Calculate contributions",
      "Prepare schedule",
      "Review calculations",
      "Submit to NIS",
      "Confirm payment",
    ],
    estimatedDays: 3,
    defaultFee: "12000.00",
    sortOrder: 13,
  },
  {
    business: "KAJ" as const,
    name: "NIS Compliance Review",
    description: "Review and rectification of NIS compliance issues",
    category: "NIS" as const,
    defaultChecklistItems: [
      "Review NIS records",
      "Identify discrepancies",
      "Calculate arrears if any",
      "Prepare rectification plan",
      "Submit corrections",
      "Confirm compliance",
    ],
    estimatedDays: 7,
    defaultFee: "25000.00",
    sortOrder: 14,
  },
  {
    business: "KAJ" as const,
    name: "Pension Application",
    description: "NIS pension claim assistance",
    category: "NIS" as const,
    defaultChecklistItems: [
      "Verify eligibility",
      "Collect required documents",
      "Complete pension forms",
      "Submit application",
      "Follow up with NIS",
      "Advise client on status",
    ],
    estimatedDays: 30,
    defaultFee: "20000.00",
    sortOrder: 15,
  },

  // Specialized Applications
  {
    business: "KAJ" as const,
    name: "Tender Document Preparation",
    description: "Preparation of tender/bid documents",
    category: "ACCOUNTING" as const,
    defaultChecklistItems: [
      "Review tender requirements",
      "Gather company documents",
      "Prepare financial statements",
      "Complete tender forms",
      "Compile supporting docs",
      "Review submission",
      "Submit tender",
    ],
    estimatedDays: 10,
    defaultFee: "50000.00",
    sortOrder: 16,
  },
  {
    business: "KAJ" as const,
    name: "Work Permit Tax Documentation",
    description: "Tax clearance and financial documents for work permits",
    category: "TAX" as const,
    defaultChecklistItems: [
      "Verify tax compliance",
      "Prepare financial summary",
      "Obtain tax clearance",
      "Compile required documents",
      "Deliver to client/GCMC",
    ],
    estimatedDays: 7,
    defaultFee: "25000.00",
    sortOrder: 17,
  },
  {
    business: "KAJ" as const,
    name: "Land Transfer Tax Matters",
    description: "Calculation and filing of land transfer taxes",
    category: "TAX" as const,
    defaultChecklistItems: [
      "Review property documents",
      "Calculate transfer tax",
      "Prepare tax forms",
      "Submit to GRA",
      "Follow up on assessment",
      "Facilitate payment",
    ],
    estimatedDays: 7,
    defaultFee: "30000.00",
    sortOrder: 18,
  },
  {
    business: "KAJ" as const,
    name: "Firearm License Application",
    description: "Financial documentation for firearm license applications",
    category: "OTHER" as const,
    defaultChecklistItems: [
      "Prepare financial statement",
      "Verify income sources",
      "Complete required forms",
      "Notarize documents",
      "Deliver to client",
    ],
    estimatedDays: 5,
    defaultFee: "20000.00",
    sortOrder: 19,
  },
];

async function seed() {
  console.log("Seeding database...");

  // Insert GCMC services
  console.log("Inserting GCMC services...");
  for (const service of gcmcServices) {
    await db.insert(serviceType).values(service).onConflictDoNothing();
  }

  // Insert KAJ services
  console.log("Inserting KAJ services...");
  for (const service of kajServices) {
    await db.insert(serviceType).values(service).onConflictDoNothing();
  }

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((error) => {
  console.error("Seeding failed:", error);
  process.exit(1);
});
