/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as StaffSetupPasswordRouteImport } from './routes/staff/setup-password'
import { Route as PortalSettingsRouteImport } from './routes/portal/settings'
import { Route as PortalResourcesRouteImport } from './routes/portal/resources'
import { Route as PortalResetPasswordRouteImport } from './routes/portal/reset-password'
import { Route as PortalRegisterRouteImport } from './routes/portal/register'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalMessagesRouteImport } from './routes/portal/messages'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalForgotPasswordRouteImport } from './routes/portal/forgot-password'
import { Route as PortalFinancialsRouteImport } from './routes/portal/financials'
import { Route as PortalDocumentsRouteImport } from './routes/portal/documents'
import { Route as PortalAppointmentsRouteImport } from './routes/portal/appointments'
import { Route as PaySuccessRouteImport } from './routes/pay/success'
import { Route as PayTokenRouteImport } from './routes/pay/$token'
import { Route as BookManageRouteImport } from './routes/book/manage'
import { Route as BookTokenRouteImport } from './routes/book/$token'
import { Route as AppTrainingIndexRouteImport } from './routes/app/training/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppServicesIndexRouteImport } from './routes/app/services/index'
import { Route as AppReportsIndexRouteImport } from './routes/app/reports/index'
import { Route as AppMattersIndexRouteImport } from './routes/app/matters/index'
import { Route as AppKnowledgeBaseIndexRouteImport } from './routes/app/knowledge-base/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/app/invoices/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/app/documents/index'
import { Route as AppClientsIndexRouteImport } from './routes/app/clients/index'
import { Route as AppCalendarIndexRouteImport } from './routes/app/calendar/index'
import { Route as AppCalculatorsIndexRouteImport } from './routes/app/calculators/index'
import { Route as AppAppointmentsIndexRouteImport } from './routes/app/appointments/index'
import { Route as AppAnalyticsIndexRouteImport } from './routes/app/analytics/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as PortalMattersMatterIdRouteImport } from './routes/portal/matters/$matter-id'
import { Route as AppTrainingNewRouteImport } from './routes/app/training/new'
import { Route as AppTrainingCalendarRouteImport } from './routes/app/training/calendar'
import { Route as AppServicesServiceIdRouteImport } from './routes/app/services/$service-id'
import { Route as AppReportsCustomRouteImport } from './routes/app/reports/custom'
import { Route as AppReportsAgingRouteImport } from './routes/app/reports/aging'
import { Route as AppMattersWizardRouteImport } from './routes/app/matters/wizard'
import { Route as AppMattersNewRouteImport } from './routes/app/matters/new'
import { Route as AppMattersMatterIdRouteImport } from './routes/app/matters/$matter-id'
import { Route as AppInvoicesNewRouteImport } from './routes/app/invoices/new'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/app/invoices/$invoice-id'
import { Route as AppDocumentsUploadRouteImport } from './routes/app/documents/upload'
import { Route as AppClientsOnboardRouteImport } from './routes/app/clients/onboard'
import { Route as AppClientsNewRouteImport } from './routes/app/clients/new'
import { Route as AppClientsClientIdRouteImport } from './routes/app/clients/$client-id'
import { Route as AppCalendarNewRouteImport } from './routes/app/calendar/new'
import { Route as AppCalculatorsVatRouteImport } from './routes/app/calculators/vat'
import { Route as AppCalculatorsSalaryRouteImport } from './routes/app/calculators/salary'
import { Route as AppCalculatorsPayeRouteImport } from './routes/app/calculators/paye'
import { Route as AppCalculatorsNisRouteImport } from './routes/app/calculators/nis'
import { Route as AppAppointmentsNewRouteImport } from './routes/app/appointments/new'
import { Route as AppAppointmentsCalendarRouteImport } from './routes/app/appointments/calendar'
import { Route as AppAppointmentsAppointmentIdRouteImport } from './routes/app/appointments/$appointment-id'
import { Route as AppAnalyticsAuditRouteImport } from './routes/app/analytics/audit'
import { Route as AppAdminSettingsRouteImport } from './routes/app/admin/settings'
import { Route as AppAdminRolesRouteImport } from './routes/app/admin/roles'
import { Route as AppAdminPortalInvitesRouteImport } from './routes/app/admin/portal-invites'
import { Route as AppAdminKnowledgeBaseFormsRouteImport } from './routes/app/admin/knowledge-base-forms'
import { Route as AppAdminKnowledgeBaseRouteImport } from './routes/app/admin/knowledge-base'
import { Route as AppAdminEmailTemplatesRouteImport } from './routes/app/admin/email-templates'
import { Route as AppTrainingEnrollmentsIndexRouteImport } from './routes/app/training/enrollments/index'
import { Route as AppTrainingCoursesIndexRouteImport } from './routes/app/training/courses/index'
import { Route as AppDocumentsTemplatesIndexRouteImport } from './routes/app/documents/templates/index'
import { Route as AppAdminStaffIndexRouteImport } from './routes/app/admin/staff/index'
import { Route as AppAdminServicesIndexRouteImport } from './routes/app/admin/services/index'
import { Route as AppTrainingSchedulesScheduleIdRouteImport } from './routes/app/training/schedules/$schedule-id'
import { Route as AppTrainingCoursesCourseIdRouteImport } from './routes/app/training/courses/$course-id'
import { Route as AppDocumentsTemplatesNewRouteImport } from './routes/app/documents/templates/new'
import { Route as AppDocumentsTemplatesTemplateIdRouteImport } from './routes/app/documents/templates/$template-id'
import { Route as AppClientsClientIdPortalActivityRouteImport } from './routes/app/clients/$client-id/portal-activity'
import { Route as AppAdminStaffNewRouteImport } from './routes/app/admin/staff/new'
import { Route as AppAdminStaffStaffIdRouteImport } from './routes/app/admin/staff/$staff-id'
import { Route as AppAdminServicesServiceIdRouteImport } from './routes/app/admin/services/$service-id'
import { Route as AppClientsClientIdDocumentsCollectRouteImport } from './routes/app/clients/$client-id/documents/collect'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const StaffSetupPasswordRoute = StaffSetupPasswordRouteImport.update({
  id: '/staff/setup-password',
  path: '/staff/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/portal/settings',
  path: '/portal/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalResourcesRoute = PortalResourcesRouteImport.update({
  id: '/portal/resources',
  path: '/portal/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalResetPasswordRoute = PortalResetPasswordRouteImport.update({
  id: '/portal/reset-password',
  path: '/portal/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRegisterRoute = PortalRegisterRouteImport.update({
  id: '/portal/register',
  path: '/portal/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/portal/profile',
  path: '/portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/portal/messages',
  path: '/portal/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalForgotPasswordRoute = PortalForgotPasswordRouteImport.update({
  id: '/portal/forgot-password',
  path: '/portal/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalFinancialsRoute = PortalFinancialsRouteImport.update({
  id: '/portal/financials',
  path: '/portal/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/portal/documents',
  path: '/portal/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAppointmentsRoute = PortalAppointmentsRouteImport.update({
  id: '/portal/appointments',
  path: '/portal/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySuccessRoute = PaySuccessRouteImport.update({
  id: '/pay/success',
  path: '/pay/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookManageRoute = BookManageRouteImport.update({
  id: '/book/manage',
  path: '/book/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTokenRoute = BookTokenRouteImport.update({
  id: '/book/$token',
  path: '/book/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainingIndexRoute = AppTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppMattersIndexRoute = AppMattersIndexRouteImport.update({
  id: '/matters/',
  path: '/matters/',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseIndexRoute = AppKnowledgeBaseIndexRouteImport.update({
  id: '/knowledge-base/',
  path: '/knowledge-base/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsIndexRoute = AppCalculatorsIndexRouteImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsIndexRoute = AppAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const PortalMattersMatterIdRoute = PortalMattersMatterIdRouteImport.update({
  id: '/portal/matters/$matter-id',
  path: '/portal/matters/$matter-id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainingNewRoute = AppTrainingNewRouteImport.update({
  id: '/training/new',
  path: '/training/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingCalendarRoute = AppTrainingCalendarRouteImport.update({
  id: '/training/calendar',
  path: '/training/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesServiceIdRoute = AppServicesServiceIdRouteImport.update({
  id: '/services/$service-id',
  path: '/services/$service-id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCustomRoute = AppReportsCustomRouteImport.update({
  id: '/reports/custom',
  path: '/reports/custom',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsAgingRoute = AppReportsAgingRouteImport.update({
  id: '/reports/aging',
  path: '/reports/aging',
  getParentRoute: () => AppRoute,
} as any)
const AppMattersWizardRoute = AppMattersWizardRouteImport.update({
  id: '/matters/wizard',
  path: '/matters/wizard',
  getParentRoute: () => AppRoute,
} as any)
const AppMattersNewRoute = AppMattersNewRouteImport.update({
  id: '/matters/new',
  path: '/matters/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMattersMatterIdRoute = AppMattersMatterIdRouteImport.update({
  id: '/matters/$matter-id',
  path: '/matters/$matter-id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoice-id',
  path: '/invoices/$invoice-id',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsUploadRoute = AppDocumentsUploadRouteImport.update({
  id: '/documents/upload',
  path: '/documents/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsOnboardRoute = AppClientsOnboardRouteImport.update({
  id: '/clients/onboard',
  path: '/clients/onboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$client-id',
  path: '/clients/$client-id',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarNewRoute = AppCalendarNewRouteImport.update({
  id: '/calendar/new',
  path: '/calendar/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsVatRoute = AppCalculatorsVatRouteImport.update({
  id: '/calculators/vat',
  path: '/calculators/vat',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsSalaryRoute = AppCalculatorsSalaryRouteImport.update({
  id: '/calculators/salary',
  path: '/calculators/salary',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsPayeRoute = AppCalculatorsPayeRouteImport.update({
  id: '/calculators/paye',
  path: '/calculators/paye',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsNisRoute = AppCalculatorsNisRouteImport.update({
  id: '/calculators/nis',
  path: '/calculators/nis',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsNewRoute = AppAppointmentsNewRouteImport.update({
  id: '/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsCalendarRoute = AppAppointmentsCalendarRouteImport.update({
  id: '/appointments/calendar',
  path: '/appointments/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsAppointmentIdRoute =
  AppAppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointment-id',
    path: '/appointments/$appointment-id',
    getParentRoute: () => AppRoute,
  } as any)
const AppAnalyticsAuditRoute = AppAnalyticsAuditRouteImport.update({
  id: '/analytics/audit',
  path: '/analytics/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPortalInvitesRoute = AppAdminPortalInvitesRouteImport.update({
  id: '/admin/portal-invites',
  path: '/admin/portal-invites',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminKnowledgeBaseFormsRoute =
  AppAdminKnowledgeBaseFormsRouteImport.update({
    id: '/admin/knowledge-base-forms',
    path: '/admin/knowledge-base-forms',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminKnowledgeBaseRoute = AppAdminKnowledgeBaseRouteImport.update({
  id: '/admin/knowledge-base',
  path: '/admin/knowledge-base',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmailTemplatesRoute = AppAdminEmailTemplatesRouteImport.update({
  id: '/admin/email-templates',
  path: '/admin/email-templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingEnrollmentsIndexRoute =
  AppTrainingEnrollmentsIndexRouteImport.update({
    id: '/training/enrollments/',
    path: '/training/enrollments/',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrainingCoursesIndexRoute = AppTrainingCoursesIndexRouteImport.update({
  id: '/training/courses/',
  path: '/training/courses/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsTemplatesIndexRoute =
  AppDocumentsTemplatesIndexRouteImport.update({
    id: '/documents/templates/',
    path: '/documents/templates/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminStaffIndexRoute = AppAdminStaffIndexRouteImport.update({
  id: '/admin/staff/',
  path: '/admin/staff/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminServicesIndexRoute = AppAdminServicesIndexRouteImport.update({
  id: '/admin/services/',
  path: '/admin/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingSchedulesScheduleIdRoute =
  AppTrainingSchedulesScheduleIdRouteImport.update({
    id: '/training/schedules/$schedule-id',
    path: '/training/schedules/$schedule-id',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrainingCoursesCourseIdRoute =
  AppTrainingCoursesCourseIdRouteImport.update({
    id: '/training/courses/$course-id',
    path: '/training/courses/$course-id',
    getParentRoute: () => AppRoute,
  } as any)
const AppDocumentsTemplatesNewRoute =
  AppDocumentsTemplatesNewRouteImport.update({
    id: '/documents/templates/new',
    path: '/documents/templates/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppDocumentsTemplatesTemplateIdRoute =
  AppDocumentsTemplatesTemplateIdRouteImport.update({
    id: '/documents/templates/$template-id',
    path: '/documents/templates/$template-id',
    getParentRoute: () => AppRoute,
  } as any)
const AppClientsClientIdPortalActivityRoute =
  AppClientsClientIdPortalActivityRouteImport.update({
    id: '/portal-activity',
    path: '/portal-activity',
    getParentRoute: () => AppClientsClientIdRoute,
  } as any)
const AppAdminStaffNewRoute = AppAdminStaffNewRouteImport.update({
  id: '/admin/staff/new',
  path: '/admin/staff/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStaffStaffIdRoute = AppAdminStaffStaffIdRouteImport.update({
  id: '/admin/staff/$staff-id',
  path: '/admin/staff/$staff-id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminServicesServiceIdRoute =
  AppAdminServicesServiceIdRouteImport.update({
    id: '/admin/services/$service-id',
    path: '/admin/services/$service-id',
    getParentRoute: () => AppRoute,
  } as any)
const AppClientsClientIdDocumentsCollectRoute =
  AppClientsClientIdDocumentsCollectRouteImport.update({
    id: '/documents/collect',
    path: '/documents/collect',
    getParentRoute: () => AppClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/book/$token': typeof BookTokenRoute
  '/book/manage': typeof BookManageRoute
  '/pay/$token': typeof PayTokenRoute
  '/pay/success': typeof PaySuccessRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/financials': typeof PortalFinancialsRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/register': typeof PortalRegisterRoute
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/staff/setup-password': typeof StaffSetupPasswordRoute
  '/app/': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
  '/app/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/app/admin/knowledge-base': typeof AppAdminKnowledgeBaseRoute
  '/app/admin/knowledge-base-forms': typeof AppAdminKnowledgeBaseFormsRoute
  '/app/admin/portal-invites': typeof AppAdminPortalInvitesRoute
  '/app/admin/roles': typeof AppAdminRolesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/analytics/audit': typeof AppAnalyticsAuditRoute
  '/app/appointments/$appointment-id': typeof AppAppointmentsAppointmentIdRoute
  '/app/appointments/calendar': typeof AppAppointmentsCalendarRoute
  '/app/appointments/new': typeof AppAppointmentsNewRoute
  '/app/calculators/nis': typeof AppCalculatorsNisRoute
  '/app/calculators/paye': typeof AppCalculatorsPayeRoute
  '/app/calculators/salary': typeof AppCalculatorsSalaryRoute
  '/app/calculators/vat': typeof AppCalculatorsVatRoute
  '/app/calendar/new': typeof AppCalendarNewRoute
  '/app/clients/$client-id': typeof AppClientsClientIdRouteWithChildren
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/clients/onboard': typeof AppClientsOnboardRoute
  '/app/documents/upload': typeof AppDocumentsUploadRoute
  '/app/invoices/$invoice-id': typeof AppInvoicesInvoiceIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/matters/$matter-id': typeof AppMattersMatterIdRoute
  '/app/matters/new': typeof AppMattersNewRoute
  '/app/matters/wizard': typeof AppMattersWizardRoute
  '/app/reports/aging': typeof AppReportsAgingRoute
  '/app/reports/custom': typeof AppReportsCustomRoute
  '/app/services/$service-id': typeof AppServicesServiceIdRoute
  '/app/training/calendar': typeof AppTrainingCalendarRoute
  '/app/training/new': typeof AppTrainingNewRoute
  '/portal/matters/$matter-id': typeof PortalMattersMatterIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/analytics': typeof AppAnalyticsIndexRoute
  '/app/appointments': typeof AppAppointmentsIndexRoute
  '/app/calculators': typeof AppCalculatorsIndexRoute
  '/app/calendar': typeof AppCalendarIndexRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/invoices': typeof AppInvoicesIndexRoute
  '/app/knowledge-base': typeof AppKnowledgeBaseIndexRoute
  '/app/matters': typeof AppMattersIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/services': typeof AppServicesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/training': typeof AppTrainingIndexRoute
  '/app/admin/services/$service-id': typeof AppAdminServicesServiceIdRoute
  '/app/admin/staff/$staff-id': typeof AppAdminStaffStaffIdRoute
  '/app/admin/staff/new': typeof AppAdminStaffNewRoute
  '/app/clients/$client-id/portal-activity': typeof AppClientsClientIdPortalActivityRoute
  '/app/documents/templates/$template-id': typeof AppDocumentsTemplatesTemplateIdRoute
  '/app/documents/templates/new': typeof AppDocumentsTemplatesNewRoute
  '/app/training/courses/$course-id': typeof AppTrainingCoursesCourseIdRoute
  '/app/training/schedules/$schedule-id': typeof AppTrainingSchedulesScheduleIdRoute
  '/app/admin/services': typeof AppAdminServicesIndexRoute
  '/app/admin/staff': typeof AppAdminStaffIndexRoute
  '/app/documents/templates': typeof AppDocumentsTemplatesIndexRoute
  '/app/training/courses': typeof AppTrainingCoursesIndexRoute
  '/app/training/enrollments': typeof AppTrainingEnrollmentsIndexRoute
  '/app/clients/$client-id/documents/collect': typeof AppClientsClientIdDocumentsCollectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/book/$token': typeof BookTokenRoute
  '/book/manage': typeof BookManageRoute
  '/pay/$token': typeof PayTokenRoute
  '/pay/success': typeof PaySuccessRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/financials': typeof PortalFinancialsRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/register': typeof PortalRegisterRoute
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/staff/setup-password': typeof StaffSetupPasswordRoute
  '/app': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
  '/app/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/app/admin/knowledge-base': typeof AppAdminKnowledgeBaseRoute
  '/app/admin/knowledge-base-forms': typeof AppAdminKnowledgeBaseFormsRoute
  '/app/admin/portal-invites': typeof AppAdminPortalInvitesRoute
  '/app/admin/roles': typeof AppAdminRolesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/analytics/audit': typeof AppAnalyticsAuditRoute
  '/app/appointments/$appointment-id': typeof AppAppointmentsAppointmentIdRoute
  '/app/appointments/calendar': typeof AppAppointmentsCalendarRoute
  '/app/appointments/new': typeof AppAppointmentsNewRoute
  '/app/calculators/nis': typeof AppCalculatorsNisRoute
  '/app/calculators/paye': typeof AppCalculatorsPayeRoute
  '/app/calculators/salary': typeof AppCalculatorsSalaryRoute
  '/app/calculators/vat': typeof AppCalculatorsVatRoute
  '/app/calendar/new': typeof AppCalendarNewRoute
  '/app/clients/$client-id': typeof AppClientsClientIdRouteWithChildren
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/clients/onboard': typeof AppClientsOnboardRoute
  '/app/documents/upload': typeof AppDocumentsUploadRoute
  '/app/invoices/$invoice-id': typeof AppInvoicesInvoiceIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/matters/$matter-id': typeof AppMattersMatterIdRoute
  '/app/matters/new': typeof AppMattersNewRoute
  '/app/matters/wizard': typeof AppMattersWizardRoute
  '/app/reports/aging': typeof AppReportsAgingRoute
  '/app/reports/custom': typeof AppReportsCustomRoute
  '/app/services/$service-id': typeof AppServicesServiceIdRoute
  '/app/training/calendar': typeof AppTrainingCalendarRoute
  '/app/training/new': typeof AppTrainingNewRoute
  '/portal/matters/$matter-id': typeof PortalMattersMatterIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/analytics': typeof AppAnalyticsIndexRoute
  '/app/appointments': typeof AppAppointmentsIndexRoute
  '/app/calculators': typeof AppCalculatorsIndexRoute
  '/app/calendar': typeof AppCalendarIndexRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/invoices': typeof AppInvoicesIndexRoute
  '/app/knowledge-base': typeof AppKnowledgeBaseIndexRoute
  '/app/matters': typeof AppMattersIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/services': typeof AppServicesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/training': typeof AppTrainingIndexRoute
  '/app/admin/services/$service-id': typeof AppAdminServicesServiceIdRoute
  '/app/admin/staff/$staff-id': typeof AppAdminStaffStaffIdRoute
  '/app/admin/staff/new': typeof AppAdminStaffNewRoute
  '/app/clients/$client-id/portal-activity': typeof AppClientsClientIdPortalActivityRoute
  '/app/documents/templates/$template-id': typeof AppDocumentsTemplatesTemplateIdRoute
  '/app/documents/templates/new': typeof AppDocumentsTemplatesNewRoute
  '/app/training/courses/$course-id': typeof AppTrainingCoursesCourseIdRoute
  '/app/training/schedules/$schedule-id': typeof AppTrainingSchedulesScheduleIdRoute
  '/app/admin/services': typeof AppAdminServicesIndexRoute
  '/app/admin/staff': typeof AppAdminStaffIndexRoute
  '/app/documents/templates': typeof AppDocumentsTemplatesIndexRoute
  '/app/training/courses': typeof AppTrainingCoursesIndexRoute
  '/app/training/enrollments': typeof AppTrainingEnrollmentsIndexRoute
  '/app/clients/$client-id/documents/collect': typeof AppClientsClientIdDocumentsCollectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/book/$token': typeof BookTokenRoute
  '/book/manage': typeof BookManageRoute
  '/pay/$token': typeof PayTokenRoute
  '/pay/success': typeof PaySuccessRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/financials': typeof PortalFinancialsRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/register': typeof PortalRegisterRoute
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/staff/setup-password': typeof StaffSetupPasswordRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/app/admin/knowledge-base': typeof AppAdminKnowledgeBaseRoute
  '/app/admin/knowledge-base-forms': typeof AppAdminKnowledgeBaseFormsRoute
  '/app/admin/portal-invites': typeof AppAdminPortalInvitesRoute
  '/app/admin/roles': typeof AppAdminRolesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/analytics/audit': typeof AppAnalyticsAuditRoute
  '/app/appointments/$appointment-id': typeof AppAppointmentsAppointmentIdRoute
  '/app/appointments/calendar': typeof AppAppointmentsCalendarRoute
  '/app/appointments/new': typeof AppAppointmentsNewRoute
  '/app/calculators/nis': typeof AppCalculatorsNisRoute
  '/app/calculators/paye': typeof AppCalculatorsPayeRoute
  '/app/calculators/salary': typeof AppCalculatorsSalaryRoute
  '/app/calculators/vat': typeof AppCalculatorsVatRoute
  '/app/calendar/new': typeof AppCalendarNewRoute
  '/app/clients/$client-id': typeof AppClientsClientIdRouteWithChildren
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/clients/onboard': typeof AppClientsOnboardRoute
  '/app/documents/upload': typeof AppDocumentsUploadRoute
  '/app/invoices/$invoice-id': typeof AppInvoicesInvoiceIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/matters/$matter-id': typeof AppMattersMatterIdRoute
  '/app/matters/new': typeof AppMattersNewRoute
  '/app/matters/wizard': typeof AppMattersWizardRoute
  '/app/reports/aging': typeof AppReportsAgingRoute
  '/app/reports/custom': typeof AppReportsCustomRoute
  '/app/services/$service-id': typeof AppServicesServiceIdRoute
  '/app/training/calendar': typeof AppTrainingCalendarRoute
  '/app/training/new': typeof AppTrainingNewRoute
  '/portal/matters/$matter-id': typeof PortalMattersMatterIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/appointments/': typeof AppAppointmentsIndexRoute
  '/app/calculators/': typeof AppCalculatorsIndexRoute
  '/app/calendar/': typeof AppCalendarIndexRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/knowledge-base/': typeof AppKnowledgeBaseIndexRoute
  '/app/matters/': typeof AppMattersIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/services/': typeof AppServicesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/training/': typeof AppTrainingIndexRoute
  '/app/admin/services/$service-id': typeof AppAdminServicesServiceIdRoute
  '/app/admin/staff/$staff-id': typeof AppAdminStaffStaffIdRoute
  '/app/admin/staff/new': typeof AppAdminStaffNewRoute
  '/app/clients/$client-id/portal-activity': typeof AppClientsClientIdPortalActivityRoute
  '/app/documents/templates/$template-id': typeof AppDocumentsTemplatesTemplateIdRoute
  '/app/documents/templates/new': typeof AppDocumentsTemplatesNewRoute
  '/app/training/courses/$course-id': typeof AppTrainingCoursesCourseIdRoute
  '/app/training/schedules/$schedule-id': typeof AppTrainingSchedulesScheduleIdRoute
  '/app/admin/services/': typeof AppAdminServicesIndexRoute
  '/app/admin/staff/': typeof AppAdminStaffIndexRoute
  '/app/documents/templates/': typeof AppDocumentsTemplatesIndexRoute
  '/app/training/courses/': typeof AppTrainingCoursesIndexRoute
  '/app/training/enrollments/': typeof AppTrainingEnrollmentsIndexRoute
  '/app/clients/$client-id/documents/collect': typeof AppClientsClientIdDocumentsCollectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/book/$token'
    | '/book/manage'
    | '/pay/$token'
    | '/pay/success'
    | '/portal/appointments'
    | '/portal/documents'
    | '/portal/financials'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/profile'
    | '/portal/register'
    | '/portal/reset-password'
    | '/portal/resources'
    | '/portal/settings'
    | '/staff/setup-password'
    | '/app/'
    | '/portal'
    | '/app/admin/email-templates'
    | '/app/admin/knowledge-base'
    | '/app/admin/knowledge-base-forms'
    | '/app/admin/portal-invites'
    | '/app/admin/roles'
    | '/app/admin/settings'
    | '/app/analytics/audit'
    | '/app/appointments/$appointment-id'
    | '/app/appointments/calendar'
    | '/app/appointments/new'
    | '/app/calculators/nis'
    | '/app/calculators/paye'
    | '/app/calculators/salary'
    | '/app/calculators/vat'
    | '/app/calendar/new'
    | '/app/clients/$client-id'
    | '/app/clients/new'
    | '/app/clients/onboard'
    | '/app/documents/upload'
    | '/app/invoices/$invoice-id'
    | '/app/invoices/new'
    | '/app/matters/$matter-id'
    | '/app/matters/new'
    | '/app/matters/wizard'
    | '/app/reports/aging'
    | '/app/reports/custom'
    | '/app/services/$service-id'
    | '/app/training/calendar'
    | '/app/training/new'
    | '/portal/matters/$matter-id'
    | '/app/admin'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/calculators'
    | '/app/calendar'
    | '/app/clients'
    | '/app/documents'
    | '/app/invoices'
    | '/app/knowledge-base'
    | '/app/matters'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/training'
    | '/app/admin/services/$service-id'
    | '/app/admin/staff/$staff-id'
    | '/app/admin/staff/new'
    | '/app/clients/$client-id/portal-activity'
    | '/app/documents/templates/$template-id'
    | '/app/documents/templates/new'
    | '/app/training/courses/$course-id'
    | '/app/training/schedules/$schedule-id'
    | '/app/admin/services'
    | '/app/admin/staff'
    | '/app/documents/templates'
    | '/app/training/courses'
    | '/app/training/enrollments'
    | '/app/clients/$client-id/documents/collect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/book/$token'
    | '/book/manage'
    | '/pay/$token'
    | '/pay/success'
    | '/portal/appointments'
    | '/portal/documents'
    | '/portal/financials'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/profile'
    | '/portal/register'
    | '/portal/reset-password'
    | '/portal/resources'
    | '/portal/settings'
    | '/staff/setup-password'
    | '/app'
    | '/portal'
    | '/app/admin/email-templates'
    | '/app/admin/knowledge-base'
    | '/app/admin/knowledge-base-forms'
    | '/app/admin/portal-invites'
    | '/app/admin/roles'
    | '/app/admin/settings'
    | '/app/analytics/audit'
    | '/app/appointments/$appointment-id'
    | '/app/appointments/calendar'
    | '/app/appointments/new'
    | '/app/calculators/nis'
    | '/app/calculators/paye'
    | '/app/calculators/salary'
    | '/app/calculators/vat'
    | '/app/calendar/new'
    | '/app/clients/$client-id'
    | '/app/clients/new'
    | '/app/clients/onboard'
    | '/app/documents/upload'
    | '/app/invoices/$invoice-id'
    | '/app/invoices/new'
    | '/app/matters/$matter-id'
    | '/app/matters/new'
    | '/app/matters/wizard'
    | '/app/reports/aging'
    | '/app/reports/custom'
    | '/app/services/$service-id'
    | '/app/training/calendar'
    | '/app/training/new'
    | '/portal/matters/$matter-id'
    | '/app/admin'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/calculators'
    | '/app/calendar'
    | '/app/clients'
    | '/app/documents'
    | '/app/invoices'
    | '/app/knowledge-base'
    | '/app/matters'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/training'
    | '/app/admin/services/$service-id'
    | '/app/admin/staff/$staff-id'
    | '/app/admin/staff/new'
    | '/app/clients/$client-id/portal-activity'
    | '/app/documents/templates/$template-id'
    | '/app/documents/templates/new'
    | '/app/training/courses/$course-id'
    | '/app/training/schedules/$schedule-id'
    | '/app/admin/services'
    | '/app/admin/staff'
    | '/app/documents/templates'
    | '/app/training/courses'
    | '/app/training/enrollments'
    | '/app/clients/$client-id/documents/collect'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/book/$token'
    | '/book/manage'
    | '/pay/$token'
    | '/pay/success'
    | '/portal/appointments'
    | '/portal/documents'
    | '/portal/financials'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/profile'
    | '/portal/register'
    | '/portal/reset-password'
    | '/portal/resources'
    | '/portal/settings'
    | '/staff/setup-password'
    | '/app/'
    | '/portal/'
    | '/app/admin/email-templates'
    | '/app/admin/knowledge-base'
    | '/app/admin/knowledge-base-forms'
    | '/app/admin/portal-invites'
    | '/app/admin/roles'
    | '/app/admin/settings'
    | '/app/analytics/audit'
    | '/app/appointments/$appointment-id'
    | '/app/appointments/calendar'
    | '/app/appointments/new'
    | '/app/calculators/nis'
    | '/app/calculators/paye'
    | '/app/calculators/salary'
    | '/app/calculators/vat'
    | '/app/calendar/new'
    | '/app/clients/$client-id'
    | '/app/clients/new'
    | '/app/clients/onboard'
    | '/app/documents/upload'
    | '/app/invoices/$invoice-id'
    | '/app/invoices/new'
    | '/app/matters/$matter-id'
    | '/app/matters/new'
    | '/app/matters/wizard'
    | '/app/reports/aging'
    | '/app/reports/custom'
    | '/app/services/$service-id'
    | '/app/training/calendar'
    | '/app/training/new'
    | '/portal/matters/$matter-id'
    | '/app/admin/'
    | '/app/analytics/'
    | '/app/appointments/'
    | '/app/calculators/'
    | '/app/calendar/'
    | '/app/clients/'
    | '/app/documents/'
    | '/app/invoices/'
    | '/app/knowledge-base/'
    | '/app/matters/'
    | '/app/reports/'
    | '/app/services/'
    | '/app/settings/'
    | '/app/training/'
    | '/app/admin/services/$service-id'
    | '/app/admin/staff/$staff-id'
    | '/app/admin/staff/new'
    | '/app/clients/$client-id/portal-activity'
    | '/app/documents/templates/$template-id'
    | '/app/documents/templates/new'
    | '/app/training/courses/$course-id'
    | '/app/training/schedules/$schedule-id'
    | '/app/admin/services/'
    | '/app/admin/staff/'
    | '/app/documents/templates/'
    | '/app/training/courses/'
    | '/app/training/enrollments/'
    | '/app/clients/$client-id/documents/collect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  BookTokenRoute: typeof BookTokenRoute
  BookManageRoute: typeof BookManageRoute
  PayTokenRoute: typeof PayTokenRoute
  PaySuccessRoute: typeof PaySuccessRoute
  PortalAppointmentsRoute: typeof PortalAppointmentsRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalFinancialsRoute: typeof PortalFinancialsRoute
  PortalForgotPasswordRoute: typeof PortalForgotPasswordRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalRegisterRoute: typeof PortalRegisterRoute
  PortalResetPasswordRoute: typeof PortalResetPasswordRoute
  PortalResourcesRoute: typeof PortalResourcesRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  StaffSetupPasswordRoute: typeof StaffSetupPasswordRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalMattersMatterIdRoute: typeof PortalMattersMatterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/staff/setup-password': {
      id: '/staff/setup-password'
      path: '/staff/setup-password'
      fullPath: '/staff/setup-password'
      preLoaderRoute: typeof StaffSetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/portal/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/resources': {
      id: '/portal/resources'
      path: '/portal/resources'
      fullPath: '/portal/resources'
      preLoaderRoute: typeof PortalResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/reset-password': {
      id: '/portal/reset-password'
      path: '/portal/reset-password'
      fullPath: '/portal/reset-password'
      preLoaderRoute: typeof PortalResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/register': {
      id: '/portal/register'
      path: '/portal/register'
      fullPath: '/portal/register'
      preLoaderRoute: typeof PortalRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/portal/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/forgot-password': {
      id: '/portal/forgot-password'
      path: '/portal/forgot-password'
      fullPath: '/portal/forgot-password'
      preLoaderRoute: typeof PortalForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/financials': {
      id: '/portal/financials'
      path: '/portal/financials'
      fullPath: '/portal/financials'
      preLoaderRoute: typeof PortalFinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/portal/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/appointments': {
      id: '/portal/appointments'
      path: '/portal/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/success': {
      id: '/pay/success'
      path: '/pay/success'
      fullPath: '/pay/success'
      preLoaderRoute: typeof PaySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/manage': {
      id: '/book/manage'
      path: '/book/manage'
      fullPath: '/book/manage'
      preLoaderRoute: typeof BookManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$token': {
      id: '/book/$token'
      path: '/book/$token'
      fullPath: '/book/$token'
      preLoaderRoute: typeof BookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/training/': {
      id: '/app/training/'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services/': {
      id: '/app/services/'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matters/': {
      id: '/app/matters/'
      path: '/matters'
      fullPath: '/app/matters'
      preLoaderRoute: typeof AppMattersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge-base/': {
      id: '/app/knowledge-base/'
      path: '/knowledge-base'
      fullPath: '/app/knowledge-base'
      preLoaderRoute: typeof AppKnowledgeBaseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices/': {
      id: '/app/invoices/'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar/': {
      id: '/app/calendar/'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculators/': {
      id: '/app/calculators/'
      path: '/calculators'
      fullPath: '/app/calculators'
      preLoaderRoute: typeof AppCalculatorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments/': {
      id: '/app/appointments/'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics/': {
      id: '/app/analytics/'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/matters/$matter-id': {
      id: '/portal/matters/$matter-id'
      path: '/portal/matters/$matter-id'
      fullPath: '/portal/matters/$matter-id'
      preLoaderRoute: typeof PortalMattersMatterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/training/new': {
      id: '/app/training/new'
      path: '/training/new'
      fullPath: '/app/training/new'
      preLoaderRoute: typeof AppTrainingNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training/calendar': {
      id: '/app/training/calendar'
      path: '/training/calendar'
      fullPath: '/app/training/calendar'
      preLoaderRoute: typeof AppTrainingCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services/$service-id': {
      id: '/app/services/$service-id'
      path: '/services/$service-id'
      fullPath: '/app/services/$service-id'
      preLoaderRoute: typeof AppServicesServiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/custom': {
      id: '/app/reports/custom'
      path: '/reports/custom'
      fullPath: '/app/reports/custom'
      preLoaderRoute: typeof AppReportsCustomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/aging': {
      id: '/app/reports/aging'
      path: '/reports/aging'
      fullPath: '/app/reports/aging'
      preLoaderRoute: typeof AppReportsAgingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matters/wizard': {
      id: '/app/matters/wizard'
      path: '/matters/wizard'
      fullPath: '/app/matters/wizard'
      preLoaderRoute: typeof AppMattersWizardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matters/new': {
      id: '/app/matters/new'
      path: '/matters/new'
      fullPath: '/app/matters/new'
      preLoaderRoute: typeof AppMattersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matters/$matter-id': {
      id: '/app/matters/$matter-id'
      path: '/matters/$matter-id'
      fullPath: '/app/matters/$matter-id'
      preLoaderRoute: typeof AppMattersMatterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices/new': {
      id: '/app/invoices/new'
      path: '/invoices/new'
      fullPath: '/app/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices/$invoice-id': {
      id: '/app/invoices/$invoice-id'
      path: '/invoices/$invoice-id'
      fullPath: '/app/invoices/$invoice-id'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/upload': {
      id: '/app/documents/upload'
      path: '/documents/upload'
      fullPath: '/app/documents/upload'
      preLoaderRoute: typeof AppDocumentsUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/onboard': {
      id: '/app/clients/onboard'
      path: '/clients/onboard'
      fullPath: '/app/clients/onboard'
      preLoaderRoute: typeof AppClientsOnboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/new': {
      id: '/app/clients/new'
      path: '/clients/new'
      fullPath: '/app/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/$client-id': {
      id: '/app/clients/$client-id'
      path: '/clients/$client-id'
      fullPath: '/app/clients/$client-id'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar/new': {
      id: '/app/calendar/new'
      path: '/calendar/new'
      fullPath: '/app/calendar/new'
      preLoaderRoute: typeof AppCalendarNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculators/vat': {
      id: '/app/calculators/vat'
      path: '/calculators/vat'
      fullPath: '/app/calculators/vat'
      preLoaderRoute: typeof AppCalculatorsVatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculators/salary': {
      id: '/app/calculators/salary'
      path: '/calculators/salary'
      fullPath: '/app/calculators/salary'
      preLoaderRoute: typeof AppCalculatorsSalaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculators/paye': {
      id: '/app/calculators/paye'
      path: '/calculators/paye'
      fullPath: '/app/calculators/paye'
      preLoaderRoute: typeof AppCalculatorsPayeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculators/nis': {
      id: '/app/calculators/nis'
      path: '/calculators/nis'
      fullPath: '/app/calculators/nis'
      preLoaderRoute: typeof AppCalculatorsNisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments/new': {
      id: '/app/appointments/new'
      path: '/appointments/new'
      fullPath: '/app/appointments/new'
      preLoaderRoute: typeof AppAppointmentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments/calendar': {
      id: '/app/appointments/calendar'
      path: '/appointments/calendar'
      fullPath: '/app/appointments/calendar'
      preLoaderRoute: typeof AppAppointmentsCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments/$appointment-id': {
      id: '/app/appointments/$appointment-id'
      path: '/appointments/$appointment-id'
      fullPath: '/app/appointments/$appointment-id'
      preLoaderRoute: typeof AppAppointmentsAppointmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics/audit': {
      id: '/app/analytics/audit'
      path: '/analytics/audit'
      fullPath: '/app/analytics/audit'
      preLoaderRoute: typeof AppAnalyticsAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/admin/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/roles': {
      id: '/app/admin/roles'
      path: '/admin/roles'
      fullPath: '/app/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/portal-invites': {
      id: '/app/admin/portal-invites'
      path: '/admin/portal-invites'
      fullPath: '/app/admin/portal-invites'
      preLoaderRoute: typeof AppAdminPortalInvitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/knowledge-base-forms': {
      id: '/app/admin/knowledge-base-forms'
      path: '/admin/knowledge-base-forms'
      fullPath: '/app/admin/knowledge-base-forms'
      preLoaderRoute: typeof AppAdminKnowledgeBaseFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/knowledge-base': {
      id: '/app/admin/knowledge-base'
      path: '/admin/knowledge-base'
      fullPath: '/app/admin/knowledge-base'
      preLoaderRoute: typeof AppAdminKnowledgeBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/email-templates': {
      id: '/app/admin/email-templates'
      path: '/admin/email-templates'
      fullPath: '/app/admin/email-templates'
      preLoaderRoute: typeof AppAdminEmailTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training/enrollments/': {
      id: '/app/training/enrollments/'
      path: '/training/enrollments'
      fullPath: '/app/training/enrollments'
      preLoaderRoute: typeof AppTrainingEnrollmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training/courses/': {
      id: '/app/training/courses/'
      path: '/training/courses'
      fullPath: '/app/training/courses'
      preLoaderRoute: typeof AppTrainingCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/templates/': {
      id: '/app/documents/templates/'
      path: '/documents/templates'
      fullPath: '/app/documents/templates'
      preLoaderRoute: typeof AppDocumentsTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/staff/': {
      id: '/app/admin/staff/'
      path: '/admin/staff'
      fullPath: '/app/admin/staff'
      preLoaderRoute: typeof AppAdminStaffIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/services/': {
      id: '/app/admin/services/'
      path: '/admin/services'
      fullPath: '/app/admin/services'
      preLoaderRoute: typeof AppAdminServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training/schedules/$schedule-id': {
      id: '/app/training/schedules/$schedule-id'
      path: '/training/schedules/$schedule-id'
      fullPath: '/app/training/schedules/$schedule-id'
      preLoaderRoute: typeof AppTrainingSchedulesScheduleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training/courses/$course-id': {
      id: '/app/training/courses/$course-id'
      path: '/training/courses/$course-id'
      fullPath: '/app/training/courses/$course-id'
      preLoaderRoute: typeof AppTrainingCoursesCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/templates/new': {
      id: '/app/documents/templates/new'
      path: '/documents/templates/new'
      fullPath: '/app/documents/templates/new'
      preLoaderRoute: typeof AppDocumentsTemplatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/templates/$template-id': {
      id: '/app/documents/templates/$template-id'
      path: '/documents/templates/$template-id'
      fullPath: '/app/documents/templates/$template-id'
      preLoaderRoute: typeof AppDocumentsTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/$client-id/portal-activity': {
      id: '/app/clients/$client-id/portal-activity'
      path: '/portal-activity'
      fullPath: '/app/clients/$client-id/portal-activity'
      preLoaderRoute: typeof AppClientsClientIdPortalActivityRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
    '/app/admin/staff/new': {
      id: '/app/admin/staff/new'
      path: '/admin/staff/new'
      fullPath: '/app/admin/staff/new'
      preLoaderRoute: typeof AppAdminStaffNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/staff/$staff-id': {
      id: '/app/admin/staff/$staff-id'
      path: '/admin/staff/$staff-id'
      fullPath: '/app/admin/staff/$staff-id'
      preLoaderRoute: typeof AppAdminStaffStaffIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/services/$service-id': {
      id: '/app/admin/services/$service-id'
      path: '/admin/services/$service-id'
      fullPath: '/app/admin/services/$service-id'
      preLoaderRoute: typeof AppAdminServicesServiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/$client-id/documents/collect': {
      id: '/app/clients/$client-id/documents/collect'
      path: '/documents/collect'
      fullPath: '/app/clients/$client-id/documents/collect'
      preLoaderRoute: typeof AppClientsClientIdDocumentsCollectRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
  }
}

interface AppClientsClientIdRouteChildren {
  AppClientsClientIdPortalActivityRoute: typeof AppClientsClientIdPortalActivityRoute
  AppClientsClientIdDocumentsCollectRoute: typeof AppClientsClientIdDocumentsCollectRoute
}

const AppClientsClientIdRouteChildren: AppClientsClientIdRouteChildren = {
  AppClientsClientIdPortalActivityRoute: AppClientsClientIdPortalActivityRoute,
  AppClientsClientIdDocumentsCollectRoute:
    AppClientsClientIdDocumentsCollectRoute,
}

const AppClientsClientIdRouteWithChildren =
  AppClientsClientIdRoute._addFileChildren(AppClientsClientIdRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAdminEmailTemplatesRoute: typeof AppAdminEmailTemplatesRoute
  AppAdminKnowledgeBaseRoute: typeof AppAdminKnowledgeBaseRoute
  AppAdminKnowledgeBaseFormsRoute: typeof AppAdminKnowledgeBaseFormsRoute
  AppAdminPortalInvitesRoute: typeof AppAdminPortalInvitesRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAnalyticsAuditRoute: typeof AppAnalyticsAuditRoute
  AppAppointmentsAppointmentIdRoute: typeof AppAppointmentsAppointmentIdRoute
  AppAppointmentsCalendarRoute: typeof AppAppointmentsCalendarRoute
  AppAppointmentsNewRoute: typeof AppAppointmentsNewRoute
  AppCalculatorsNisRoute: typeof AppCalculatorsNisRoute
  AppCalculatorsPayeRoute: typeof AppCalculatorsPayeRoute
  AppCalculatorsSalaryRoute: typeof AppCalculatorsSalaryRoute
  AppCalculatorsVatRoute: typeof AppCalculatorsVatRoute
  AppCalendarNewRoute: typeof AppCalendarNewRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRouteWithChildren
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppClientsOnboardRoute: typeof AppClientsOnboardRoute
  AppDocumentsUploadRoute: typeof AppDocumentsUploadRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppMattersMatterIdRoute: typeof AppMattersMatterIdRoute
  AppMattersNewRoute: typeof AppMattersNewRoute
  AppMattersWizardRoute: typeof AppMattersWizardRoute
  AppReportsAgingRoute: typeof AppReportsAgingRoute
  AppReportsCustomRoute: typeof AppReportsCustomRoute
  AppServicesServiceIdRoute: typeof AppServicesServiceIdRoute
  AppTrainingCalendarRoute: typeof AppTrainingCalendarRoute
  AppTrainingNewRoute: typeof AppTrainingNewRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
  AppAppointmentsIndexRoute: typeof AppAppointmentsIndexRoute
  AppCalculatorsIndexRoute: typeof AppCalculatorsIndexRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppKnowledgeBaseIndexRoute: typeof AppKnowledgeBaseIndexRoute
  AppMattersIndexRoute: typeof AppMattersIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTrainingIndexRoute: typeof AppTrainingIndexRoute
  AppAdminServicesServiceIdRoute: typeof AppAdminServicesServiceIdRoute
  AppAdminStaffStaffIdRoute: typeof AppAdminStaffStaffIdRoute
  AppAdminStaffNewRoute: typeof AppAdminStaffNewRoute
  AppDocumentsTemplatesTemplateIdRoute: typeof AppDocumentsTemplatesTemplateIdRoute
  AppDocumentsTemplatesNewRoute: typeof AppDocumentsTemplatesNewRoute
  AppTrainingCoursesCourseIdRoute: typeof AppTrainingCoursesCourseIdRoute
  AppTrainingSchedulesScheduleIdRoute: typeof AppTrainingSchedulesScheduleIdRoute
  AppAdminServicesIndexRoute: typeof AppAdminServicesIndexRoute
  AppAdminStaffIndexRoute: typeof AppAdminStaffIndexRoute
  AppDocumentsTemplatesIndexRoute: typeof AppDocumentsTemplatesIndexRoute
  AppTrainingCoursesIndexRoute: typeof AppTrainingCoursesIndexRoute
  AppTrainingEnrollmentsIndexRoute: typeof AppTrainingEnrollmentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAdminEmailTemplatesRoute: AppAdminEmailTemplatesRoute,
  AppAdminKnowledgeBaseRoute: AppAdminKnowledgeBaseRoute,
  AppAdminKnowledgeBaseFormsRoute: AppAdminKnowledgeBaseFormsRoute,
  AppAdminPortalInvitesRoute: AppAdminPortalInvitesRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAnalyticsAuditRoute: AppAnalyticsAuditRoute,
  AppAppointmentsAppointmentIdRoute: AppAppointmentsAppointmentIdRoute,
  AppAppointmentsCalendarRoute: AppAppointmentsCalendarRoute,
  AppAppointmentsNewRoute: AppAppointmentsNewRoute,
  AppCalculatorsNisRoute: AppCalculatorsNisRoute,
  AppCalculatorsPayeRoute: AppCalculatorsPayeRoute,
  AppCalculatorsSalaryRoute: AppCalculatorsSalaryRoute,
  AppCalculatorsVatRoute: AppCalculatorsVatRoute,
  AppCalendarNewRoute: AppCalendarNewRoute,
  AppClientsClientIdRoute: AppClientsClientIdRouteWithChildren,
  AppClientsNewRoute: AppClientsNewRoute,
  AppClientsOnboardRoute: AppClientsOnboardRoute,
  AppDocumentsUploadRoute: AppDocumentsUploadRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppMattersMatterIdRoute: AppMattersMatterIdRoute,
  AppMattersNewRoute: AppMattersNewRoute,
  AppMattersWizardRoute: AppMattersWizardRoute,
  AppReportsAgingRoute: AppReportsAgingRoute,
  AppReportsCustomRoute: AppReportsCustomRoute,
  AppServicesServiceIdRoute: AppServicesServiceIdRoute,
  AppTrainingCalendarRoute: AppTrainingCalendarRoute,
  AppTrainingNewRoute: AppTrainingNewRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
  AppAppointmentsIndexRoute: AppAppointmentsIndexRoute,
  AppCalculatorsIndexRoute: AppCalculatorsIndexRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppKnowledgeBaseIndexRoute: AppKnowledgeBaseIndexRoute,
  AppMattersIndexRoute: AppMattersIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTrainingIndexRoute: AppTrainingIndexRoute,
  AppAdminServicesServiceIdRoute: AppAdminServicesServiceIdRoute,
  AppAdminStaffStaffIdRoute: AppAdminStaffStaffIdRoute,
  AppAdminStaffNewRoute: AppAdminStaffNewRoute,
  AppDocumentsTemplatesTemplateIdRoute: AppDocumentsTemplatesTemplateIdRoute,
  AppDocumentsTemplatesNewRoute: AppDocumentsTemplatesNewRoute,
  AppTrainingCoursesCourseIdRoute: AppTrainingCoursesCourseIdRoute,
  AppTrainingSchedulesScheduleIdRoute: AppTrainingSchedulesScheduleIdRoute,
  AppAdminServicesIndexRoute: AppAdminServicesIndexRoute,
  AppAdminStaffIndexRoute: AppAdminStaffIndexRoute,
  AppDocumentsTemplatesIndexRoute: AppDocumentsTemplatesIndexRoute,
  AppTrainingCoursesIndexRoute: AppTrainingCoursesIndexRoute,
  AppTrainingEnrollmentsIndexRoute: AppTrainingEnrollmentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  BookTokenRoute: BookTokenRoute,
  BookManageRoute: BookManageRoute,
  PayTokenRoute: PayTokenRoute,
  PaySuccessRoute: PaySuccessRoute,
  PortalAppointmentsRoute: PortalAppointmentsRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalFinancialsRoute: PortalFinancialsRoute,
  PortalForgotPasswordRoute: PortalForgotPasswordRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalRegisterRoute: PortalRegisterRoute,
  PortalResetPasswordRoute: PortalResetPasswordRoute,
  PortalResourcesRoute: PortalResourcesRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  StaffSetupPasswordRoute: StaffSetupPasswordRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalMattersMatterIdRoute: PortalMattersMatterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
