/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as StaffSetupPasswordRouteImport } from './routes/staff/setup-password'
import { Route as PortalRegisterRouteImport } from './routes/portal/register'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalFinancialsRouteImport } from './routes/portal/financials'
import { Route as PortalDocumentsRouteImport } from './routes/portal/documents'
import { Route as PortalAppointmentsRouteImport } from './routes/portal/appointments'
import { Route as AppTrainingIndexRouteImport } from './routes/app/training/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppServicesIndexRouteImport } from './routes/app/services/index'
import { Route as AppReportsIndexRouteImport } from './routes/app/reports/index'
import { Route as AppMattersIndexRouteImport } from './routes/app/matters/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/app/invoices/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/app/documents/index'
import { Route as AppClientsIndexRouteImport } from './routes/app/clients/index'
import { Route as AppCalendarIndexRouteImport } from './routes/app/calendar/index'
import { Route as AppCalculatorsIndexRouteImport } from './routes/app/calculators/index'
import { Route as AppAppointmentsIndexRouteImport } from './routes/app/appointments/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as PortalMattersMatterIdRouteImport } from './routes/portal/matters/$matter-id'
import { Route as AppTrainingNewRouteImport } from './routes/app/training/new'
import { Route as AppServicesServiceIdRouteImport } from './routes/app/services/$service-id'
import { Route as AppReportsCustomRouteImport } from './routes/app/reports/custom'
import { Route as AppMattersNewRouteImport } from './routes/app/matters/new'
import { Route as AppMattersMatterIdRouteImport } from './routes/app/matters/$matter-id'
import { Route as AppInvoicesNewRouteImport } from './routes/app/invoices/new'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/app/invoices/$invoice-id'
import { Route as AppDocumentsUploadRouteImport } from './routes/app/documents/upload'
import { Route as AppClientsOnboardRouteImport } from './routes/app/clients/onboard'
import { Route as AppClientsNewRouteImport } from './routes/app/clients/new'
import { Route as AppClientsClientIdRouteImport } from './routes/app/clients/$client-id'
import { Route as AppCalendarNewRouteImport } from './routes/app/calendar/new'
import { Route as AppCalculatorsVatRouteImport } from './routes/app/calculators/vat'
import { Route as AppCalculatorsPayeRouteImport } from './routes/app/calculators/paye'
import { Route as AppCalculatorsNisRouteImport } from './routes/app/calculators/nis'
import { Route as AppAppointmentsNewRouteImport } from './routes/app/appointments/new'
import { Route as AppDocumentsTemplatesIndexRouteImport } from './routes/app/documents/templates/index'
import { Route as AppAdminStaffIndexRouteImport } from './routes/app/admin/staff/index'
import { Route as AppAdminServicesIndexRouteImport } from './routes/app/admin/services/index'
import { Route as AppTrainingSchedulesScheduleIdRouteImport } from './routes/app/training/schedules/$schedule-id'
import { Route as AppTrainingCoursesCourseIdRouteImport } from './routes/app/training/courses/$course-id'
import { Route as AppDocumentsTemplatesNewRouteImport } from './routes/app/documents/templates/new'
import { Route as AppDocumentsTemplatesTemplateIdRouteImport } from './routes/app/documents/templates/$template-id'
import { Route as AppAdminStaffNewRouteImport } from './routes/app/admin/staff/new'
import { Route as AppAdminStaffStaffIdRouteImport } from './routes/app/admin/staff/$staff-id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const StaffSetupPasswordRoute = StaffSetupPasswordRouteImport.update({
  id: '/staff/setup-password',
  path: '/staff/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRegisterRoute = PortalRegisterRouteImport.update({
  id: '/portal/register',
  path: '/portal/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/portal/profile',
  path: '/portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalFinancialsRoute = PortalFinancialsRouteImport.update({
  id: '/portal/financials',
  path: '/portal/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/portal/documents',
  path: '/portal/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAppointmentsRoute = PortalAppointmentsRouteImport.update({
  id: '/portal/appointments',
  path: '/portal/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainingIndexRoute = AppTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppMattersIndexRoute = AppMattersIndexRouteImport.update({
  id: '/matters/',
  path: '/matters/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsIndexRoute = AppCalculatorsIndexRouteImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsIndexRoute = AppAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const PortalMattersMatterIdRoute = PortalMattersMatterIdRouteImport.update({
  id: '/portal/matters/$matter-id',
  path: '/portal/matters/$matter-id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainingNewRoute = AppTrainingNewRouteImport.update({
  id: '/training/new',
  path: '/training/new',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesServiceIdRoute = AppServicesServiceIdRouteImport.update({
  id: '/services/$service-id',
  path: '/services/$service-id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCustomRoute = AppReportsCustomRouteImport.update({
  id: '/reports/custom',
  path: '/reports/custom',
  getParentRoute: () => AppRoute,
} as any)
const AppMattersNewRoute = AppMattersNewRouteImport.update({
  id: '/matters/new',
  path: '/matters/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMattersMatterIdRoute = AppMattersMatterIdRouteImport.update({
  id: '/matters/$matter-id',
  path: '/matters/$matter-id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoice-id',
  path: '/invoices/$invoice-id',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsUploadRoute = AppDocumentsUploadRouteImport.update({
  id: '/documents/upload',
  path: '/documents/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsOnboardRoute = AppClientsOnboardRouteImport.update({
  id: '/clients/onboard',
  path: '/clients/onboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$client-id',
  path: '/clients/$client-id',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarNewRoute = AppCalendarNewRouteImport.update({
  id: '/calendar/new',
  path: '/calendar/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsVatRoute = AppCalculatorsVatRouteImport.update({
  id: '/calculators/vat',
  path: '/calculators/vat',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsPayeRoute = AppCalculatorsPayeRouteImport.update({
  id: '/calculators/paye',
  path: '/calculators/paye',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsNisRoute = AppCalculatorsNisRouteImport.update({
  id: '/calculators/nis',
  path: '/calculators/nis',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsNewRoute = AppAppointmentsNewRouteImport.update({
  id: '/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsTemplatesIndexRoute =
  AppDocumentsTemplatesIndexRouteImport.update({
    id: '/documents/templates/',
    path: '/documents/templates/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminStaffIndexRoute = AppAdminStaffIndexRouteImport.update({
  id: '/admin/staff/',
  path: '/admin/staff/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminServicesIndexRoute = AppAdminServicesIndexRouteImport.update({
  id: '/admin/services/',
  path: '/admin/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingSchedulesScheduleIdRoute =
  AppTrainingSchedulesScheduleIdRouteImport.update({
    id: '/training/schedules/$schedule-id',
    path: '/training/schedules/$schedule-id',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrainingCoursesCourseIdRoute =
  AppTrainingCoursesCourseIdRouteImport.update({
    id: '/training/courses/$course-id',
    path: '/training/courses/$course-id',
    getParentRoute: () => AppRoute,
  } as any)
const AppDocumentsTemplatesNewRoute =
  AppDocumentsTemplatesNewRouteImport.update({
    id: '/documents/templates/new',
    path: '/documents/templates/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppDocumentsTemplatesTemplateIdRoute =
  AppDocumentsTemplatesTemplateIdRouteImport.update({
    id: '/documents/templates/$template-id',
    path: '/documents/templates/$template-id',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminStaffNewRoute = AppAdminStaffNewRouteImport.update({
  id: '/admin/staff/new',
  path: '/admin/staff/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStaffStaffIdRoute = AppAdminStaffStaffIdRouteImport.update({
  id: '/admin/staff/$staff-id',
  path: '/admin/staff/$staff-id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/financials': typeof PortalFinancialsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/register': typeof PortalRegisterRoute
  '/staff/setup-password': typeof StaffSetupPasswordRoute
  '/app/': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
  '/app/appointments/new': typeof AppAppointmentsNewRoute
  '/app/calculators/nis': typeof AppCalculatorsNisRoute
  '/app/calculators/paye': typeof AppCalculatorsPayeRoute
  '/app/calculators/vat': typeof AppCalculatorsVatRoute
  '/app/calendar/new': typeof AppCalendarNewRoute
  '/app/clients/$client-id': typeof AppClientsClientIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/clients/onboard': typeof AppClientsOnboardRoute
  '/app/documents/upload': typeof AppDocumentsUploadRoute
  '/app/invoices/$invoice-id': typeof AppInvoicesInvoiceIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/matters/$matter-id': typeof AppMattersMatterIdRoute
  '/app/matters/new': typeof AppMattersNewRoute
  '/app/reports/custom': typeof AppReportsCustomRoute
  '/app/services/$service-id': typeof AppServicesServiceIdRoute
  '/app/training/new': typeof AppTrainingNewRoute
  '/portal/matters/$matter-id': typeof PortalMattersMatterIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/appointments': typeof AppAppointmentsIndexRoute
  '/app/calculators': typeof AppCalculatorsIndexRoute
  '/app/calendar': typeof AppCalendarIndexRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/invoices': typeof AppInvoicesIndexRoute
  '/app/matters': typeof AppMattersIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/services': typeof AppServicesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/training': typeof AppTrainingIndexRoute
  '/app/admin/staff/$staff-id': typeof AppAdminStaffStaffIdRoute
  '/app/admin/staff/new': typeof AppAdminStaffNewRoute
  '/app/documents/templates/$template-id': typeof AppDocumentsTemplatesTemplateIdRoute
  '/app/documents/templates/new': typeof AppDocumentsTemplatesNewRoute
  '/app/training/courses/$course-id': typeof AppTrainingCoursesCourseIdRoute
  '/app/training/schedules/$schedule-id': typeof AppTrainingSchedulesScheduleIdRoute
  '/app/admin/services': typeof AppAdminServicesIndexRoute
  '/app/admin/staff': typeof AppAdminStaffIndexRoute
  '/app/documents/templates': typeof AppDocumentsTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/financials': typeof PortalFinancialsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/register': typeof PortalRegisterRoute
  '/staff/setup-password': typeof StaffSetupPasswordRoute
  '/app': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
  '/app/appointments/new': typeof AppAppointmentsNewRoute
  '/app/calculators/nis': typeof AppCalculatorsNisRoute
  '/app/calculators/paye': typeof AppCalculatorsPayeRoute
  '/app/calculators/vat': typeof AppCalculatorsVatRoute
  '/app/calendar/new': typeof AppCalendarNewRoute
  '/app/clients/$client-id': typeof AppClientsClientIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/clients/onboard': typeof AppClientsOnboardRoute
  '/app/documents/upload': typeof AppDocumentsUploadRoute
  '/app/invoices/$invoice-id': typeof AppInvoicesInvoiceIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/matters/$matter-id': typeof AppMattersMatterIdRoute
  '/app/matters/new': typeof AppMattersNewRoute
  '/app/reports/custom': typeof AppReportsCustomRoute
  '/app/services/$service-id': typeof AppServicesServiceIdRoute
  '/app/training/new': typeof AppTrainingNewRoute
  '/portal/matters/$matter-id': typeof PortalMattersMatterIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/appointments': typeof AppAppointmentsIndexRoute
  '/app/calculators': typeof AppCalculatorsIndexRoute
  '/app/calendar': typeof AppCalendarIndexRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/invoices': typeof AppInvoicesIndexRoute
  '/app/matters': typeof AppMattersIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/services': typeof AppServicesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/training': typeof AppTrainingIndexRoute
  '/app/admin/staff/$staff-id': typeof AppAdminStaffStaffIdRoute
  '/app/admin/staff/new': typeof AppAdminStaffNewRoute
  '/app/documents/templates/$template-id': typeof AppDocumentsTemplatesTemplateIdRoute
  '/app/documents/templates/new': typeof AppDocumentsTemplatesNewRoute
  '/app/training/courses/$course-id': typeof AppTrainingCoursesCourseIdRoute
  '/app/training/schedules/$schedule-id': typeof AppTrainingSchedulesScheduleIdRoute
  '/app/admin/services': typeof AppAdminServicesIndexRoute
  '/app/admin/staff': typeof AppAdminStaffIndexRoute
  '/app/documents/templates': typeof AppDocumentsTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/financials': typeof PortalFinancialsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/register': typeof PortalRegisterRoute
  '/staff/setup-password': typeof StaffSetupPasswordRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/appointments/new': typeof AppAppointmentsNewRoute
  '/app/calculators/nis': typeof AppCalculatorsNisRoute
  '/app/calculators/paye': typeof AppCalculatorsPayeRoute
  '/app/calculators/vat': typeof AppCalculatorsVatRoute
  '/app/calendar/new': typeof AppCalendarNewRoute
  '/app/clients/$client-id': typeof AppClientsClientIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/clients/onboard': typeof AppClientsOnboardRoute
  '/app/documents/upload': typeof AppDocumentsUploadRoute
  '/app/invoices/$invoice-id': typeof AppInvoicesInvoiceIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/matters/$matter-id': typeof AppMattersMatterIdRoute
  '/app/matters/new': typeof AppMattersNewRoute
  '/app/reports/custom': typeof AppReportsCustomRoute
  '/app/services/$service-id': typeof AppServicesServiceIdRoute
  '/app/training/new': typeof AppTrainingNewRoute
  '/portal/matters/$matter-id': typeof PortalMattersMatterIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/appointments/': typeof AppAppointmentsIndexRoute
  '/app/calculators/': typeof AppCalculatorsIndexRoute
  '/app/calendar/': typeof AppCalendarIndexRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/matters/': typeof AppMattersIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/services/': typeof AppServicesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/training/': typeof AppTrainingIndexRoute
  '/app/admin/staff/$staff-id': typeof AppAdminStaffStaffIdRoute
  '/app/admin/staff/new': typeof AppAdminStaffNewRoute
  '/app/documents/templates/$template-id': typeof AppDocumentsTemplatesTemplateIdRoute
  '/app/documents/templates/new': typeof AppDocumentsTemplatesNewRoute
  '/app/training/courses/$course-id': typeof AppTrainingCoursesCourseIdRoute
  '/app/training/schedules/$schedule-id': typeof AppTrainingSchedulesScheduleIdRoute
  '/app/admin/services/': typeof AppAdminServicesIndexRoute
  '/app/admin/staff/': typeof AppAdminStaffIndexRoute
  '/app/documents/templates/': typeof AppDocumentsTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/portal/appointments'
    | '/portal/documents'
    | '/portal/financials'
    | '/portal/login'
    | '/portal/profile'
    | '/portal/register'
    | '/staff/setup-password'
    | '/app/'
    | '/portal'
    | '/app/appointments/new'
    | '/app/calculators/nis'
    | '/app/calculators/paye'
    | '/app/calculators/vat'
    | '/app/calendar/new'
    | '/app/clients/$client-id'
    | '/app/clients/new'
    | '/app/clients/onboard'
    | '/app/documents/upload'
    | '/app/invoices/$invoice-id'
    | '/app/invoices/new'
    | '/app/matters/$matter-id'
    | '/app/matters/new'
    | '/app/reports/custom'
    | '/app/services/$service-id'
    | '/app/training/new'
    | '/portal/matters/$matter-id'
    | '/app/admin'
    | '/app/appointments'
    | '/app/calculators'
    | '/app/calendar'
    | '/app/clients'
    | '/app/documents'
    | '/app/invoices'
    | '/app/matters'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/training'
    | '/app/admin/staff/$staff-id'
    | '/app/admin/staff/new'
    | '/app/documents/templates/$template-id'
    | '/app/documents/templates/new'
    | '/app/training/courses/$course-id'
    | '/app/training/schedules/$schedule-id'
    | '/app/admin/services'
    | '/app/admin/staff'
    | '/app/documents/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/portal/appointments'
    | '/portal/documents'
    | '/portal/financials'
    | '/portal/login'
    | '/portal/profile'
    | '/portal/register'
    | '/staff/setup-password'
    | '/app'
    | '/portal'
    | '/app/appointments/new'
    | '/app/calculators/nis'
    | '/app/calculators/paye'
    | '/app/calculators/vat'
    | '/app/calendar/new'
    | '/app/clients/$client-id'
    | '/app/clients/new'
    | '/app/clients/onboard'
    | '/app/documents/upload'
    | '/app/invoices/$invoice-id'
    | '/app/invoices/new'
    | '/app/matters/$matter-id'
    | '/app/matters/new'
    | '/app/reports/custom'
    | '/app/services/$service-id'
    | '/app/training/new'
    | '/portal/matters/$matter-id'
    | '/app/admin'
    | '/app/appointments'
    | '/app/calculators'
    | '/app/calendar'
    | '/app/clients'
    | '/app/documents'
    | '/app/invoices'
    | '/app/matters'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/training'
    | '/app/admin/staff/$staff-id'
    | '/app/admin/staff/new'
    | '/app/documents/templates/$template-id'
    | '/app/documents/templates/new'
    | '/app/training/courses/$course-id'
    | '/app/training/schedules/$schedule-id'
    | '/app/admin/services'
    | '/app/admin/staff'
    | '/app/documents/templates'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/portal/appointments'
    | '/portal/documents'
    | '/portal/financials'
    | '/portal/login'
    | '/portal/profile'
    | '/portal/register'
    | '/staff/setup-password'
    | '/app/'
    | '/portal/'
    | '/app/appointments/new'
    | '/app/calculators/nis'
    | '/app/calculators/paye'
    | '/app/calculators/vat'
    | '/app/calendar/new'
    | '/app/clients/$client-id'
    | '/app/clients/new'
    | '/app/clients/onboard'
    | '/app/documents/upload'
    | '/app/invoices/$invoice-id'
    | '/app/invoices/new'
    | '/app/matters/$matter-id'
    | '/app/matters/new'
    | '/app/reports/custom'
    | '/app/services/$service-id'
    | '/app/training/new'
    | '/portal/matters/$matter-id'
    | '/app/admin/'
    | '/app/appointments/'
    | '/app/calculators/'
    | '/app/calendar/'
    | '/app/clients/'
    | '/app/documents/'
    | '/app/invoices/'
    | '/app/matters/'
    | '/app/reports/'
    | '/app/services/'
    | '/app/settings/'
    | '/app/training/'
    | '/app/admin/staff/$staff-id'
    | '/app/admin/staff/new'
    | '/app/documents/templates/$template-id'
    | '/app/documents/templates/new'
    | '/app/training/courses/$course-id'
    | '/app/training/schedules/$schedule-id'
    | '/app/admin/services/'
    | '/app/admin/staff/'
    | '/app/documents/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PortalAppointmentsRoute: typeof PortalAppointmentsRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalFinancialsRoute: typeof PortalFinancialsRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalRegisterRoute: typeof PortalRegisterRoute
  StaffSetupPasswordRoute: typeof StaffSetupPasswordRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalMattersMatterIdRoute: typeof PortalMattersMatterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/staff/setup-password': {
      id: '/staff/setup-password'
      path: '/staff/setup-password'
      fullPath: '/staff/setup-password'
      preLoaderRoute: typeof StaffSetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/register': {
      id: '/portal/register'
      path: '/portal/register'
      fullPath: '/portal/register'
      preLoaderRoute: typeof PortalRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/financials': {
      id: '/portal/financials'
      path: '/portal/financials'
      fullPath: '/portal/financials'
      preLoaderRoute: typeof PortalFinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/portal/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/appointments': {
      id: '/portal/appointments'
      path: '/portal/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/training/': {
      id: '/app/training/'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services/': {
      id: '/app/services/'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matters/': {
      id: '/app/matters/'
      path: '/matters'
      fullPath: '/app/matters'
      preLoaderRoute: typeof AppMattersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices/': {
      id: '/app/invoices/'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar/': {
      id: '/app/calendar/'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculators/': {
      id: '/app/calculators/'
      path: '/calculators'
      fullPath: '/app/calculators'
      preLoaderRoute: typeof AppCalculatorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments/': {
      id: '/app/appointments/'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/matters/$matter-id': {
      id: '/portal/matters/$matter-id'
      path: '/portal/matters/$matter-id'
      fullPath: '/portal/matters/$matter-id'
      preLoaderRoute: typeof PortalMattersMatterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/training/new': {
      id: '/app/training/new'
      path: '/training/new'
      fullPath: '/app/training/new'
      preLoaderRoute: typeof AppTrainingNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services/$service-id': {
      id: '/app/services/$service-id'
      path: '/services/$service-id'
      fullPath: '/app/services/$service-id'
      preLoaderRoute: typeof AppServicesServiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/custom': {
      id: '/app/reports/custom'
      path: '/reports/custom'
      fullPath: '/app/reports/custom'
      preLoaderRoute: typeof AppReportsCustomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matters/new': {
      id: '/app/matters/new'
      path: '/matters/new'
      fullPath: '/app/matters/new'
      preLoaderRoute: typeof AppMattersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matters/$matter-id': {
      id: '/app/matters/$matter-id'
      path: '/matters/$matter-id'
      fullPath: '/app/matters/$matter-id'
      preLoaderRoute: typeof AppMattersMatterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices/new': {
      id: '/app/invoices/new'
      path: '/invoices/new'
      fullPath: '/app/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices/$invoice-id': {
      id: '/app/invoices/$invoice-id'
      path: '/invoices/$invoice-id'
      fullPath: '/app/invoices/$invoice-id'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/upload': {
      id: '/app/documents/upload'
      path: '/documents/upload'
      fullPath: '/app/documents/upload'
      preLoaderRoute: typeof AppDocumentsUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/onboard': {
      id: '/app/clients/onboard'
      path: '/clients/onboard'
      fullPath: '/app/clients/onboard'
      preLoaderRoute: typeof AppClientsOnboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/new': {
      id: '/app/clients/new'
      path: '/clients/new'
      fullPath: '/app/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/$client-id': {
      id: '/app/clients/$client-id'
      path: '/clients/$client-id'
      fullPath: '/app/clients/$client-id'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar/new': {
      id: '/app/calendar/new'
      path: '/calendar/new'
      fullPath: '/app/calendar/new'
      preLoaderRoute: typeof AppCalendarNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculators/vat': {
      id: '/app/calculators/vat'
      path: '/calculators/vat'
      fullPath: '/app/calculators/vat'
      preLoaderRoute: typeof AppCalculatorsVatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculators/paye': {
      id: '/app/calculators/paye'
      path: '/calculators/paye'
      fullPath: '/app/calculators/paye'
      preLoaderRoute: typeof AppCalculatorsPayeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculators/nis': {
      id: '/app/calculators/nis'
      path: '/calculators/nis'
      fullPath: '/app/calculators/nis'
      preLoaderRoute: typeof AppCalculatorsNisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments/new': {
      id: '/app/appointments/new'
      path: '/appointments/new'
      fullPath: '/app/appointments/new'
      preLoaderRoute: typeof AppAppointmentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/templates/': {
      id: '/app/documents/templates/'
      path: '/documents/templates'
      fullPath: '/app/documents/templates'
      preLoaderRoute: typeof AppDocumentsTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/staff/': {
      id: '/app/admin/staff/'
      path: '/admin/staff'
      fullPath: '/app/admin/staff'
      preLoaderRoute: typeof AppAdminStaffIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/services/': {
      id: '/app/admin/services/'
      path: '/admin/services'
      fullPath: '/app/admin/services'
      preLoaderRoute: typeof AppAdminServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training/schedules/$schedule-id': {
      id: '/app/training/schedules/$schedule-id'
      path: '/training/schedules/$schedule-id'
      fullPath: '/app/training/schedules/$schedule-id'
      preLoaderRoute: typeof AppTrainingSchedulesScheduleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training/courses/$course-id': {
      id: '/app/training/courses/$course-id'
      path: '/training/courses/$course-id'
      fullPath: '/app/training/courses/$course-id'
      preLoaderRoute: typeof AppTrainingCoursesCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/templates/new': {
      id: '/app/documents/templates/new'
      path: '/documents/templates/new'
      fullPath: '/app/documents/templates/new'
      preLoaderRoute: typeof AppDocumentsTemplatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/templates/$template-id': {
      id: '/app/documents/templates/$template-id'
      path: '/documents/templates/$template-id'
      fullPath: '/app/documents/templates/$template-id'
      preLoaderRoute: typeof AppDocumentsTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/staff/new': {
      id: '/app/admin/staff/new'
      path: '/admin/staff/new'
      fullPath: '/app/admin/staff/new'
      preLoaderRoute: typeof AppAdminStaffNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/staff/$staff-id': {
      id: '/app/admin/staff/$staff-id'
      path: '/admin/staff/$staff-id'
      fullPath: '/app/admin/staff/$staff-id'
      preLoaderRoute: typeof AppAdminStaffStaffIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAppointmentsNewRoute: typeof AppAppointmentsNewRoute
  AppCalculatorsNisRoute: typeof AppCalculatorsNisRoute
  AppCalculatorsPayeRoute: typeof AppCalculatorsPayeRoute
  AppCalculatorsVatRoute: typeof AppCalculatorsVatRoute
  AppCalendarNewRoute: typeof AppCalendarNewRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppClientsOnboardRoute: typeof AppClientsOnboardRoute
  AppDocumentsUploadRoute: typeof AppDocumentsUploadRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppMattersMatterIdRoute: typeof AppMattersMatterIdRoute
  AppMattersNewRoute: typeof AppMattersNewRoute
  AppReportsCustomRoute: typeof AppReportsCustomRoute
  AppServicesServiceIdRoute: typeof AppServicesServiceIdRoute
  AppTrainingNewRoute: typeof AppTrainingNewRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAppointmentsIndexRoute: typeof AppAppointmentsIndexRoute
  AppCalculatorsIndexRoute: typeof AppCalculatorsIndexRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppMattersIndexRoute: typeof AppMattersIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTrainingIndexRoute: typeof AppTrainingIndexRoute
  AppAdminStaffStaffIdRoute: typeof AppAdminStaffStaffIdRoute
  AppAdminStaffNewRoute: typeof AppAdminStaffNewRoute
  AppDocumentsTemplatesTemplateIdRoute: typeof AppDocumentsTemplatesTemplateIdRoute
  AppDocumentsTemplatesNewRoute: typeof AppDocumentsTemplatesNewRoute
  AppTrainingCoursesCourseIdRoute: typeof AppTrainingCoursesCourseIdRoute
  AppTrainingSchedulesScheduleIdRoute: typeof AppTrainingSchedulesScheduleIdRoute
  AppAdminServicesIndexRoute: typeof AppAdminServicesIndexRoute
  AppAdminStaffIndexRoute: typeof AppAdminStaffIndexRoute
  AppDocumentsTemplatesIndexRoute: typeof AppDocumentsTemplatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAppointmentsNewRoute: AppAppointmentsNewRoute,
  AppCalculatorsNisRoute: AppCalculatorsNisRoute,
  AppCalculatorsPayeRoute: AppCalculatorsPayeRoute,
  AppCalculatorsVatRoute: AppCalculatorsVatRoute,
  AppCalendarNewRoute: AppCalendarNewRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppClientsOnboardRoute: AppClientsOnboardRoute,
  AppDocumentsUploadRoute: AppDocumentsUploadRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppMattersMatterIdRoute: AppMattersMatterIdRoute,
  AppMattersNewRoute: AppMattersNewRoute,
  AppReportsCustomRoute: AppReportsCustomRoute,
  AppServicesServiceIdRoute: AppServicesServiceIdRoute,
  AppTrainingNewRoute: AppTrainingNewRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAppointmentsIndexRoute: AppAppointmentsIndexRoute,
  AppCalculatorsIndexRoute: AppCalculatorsIndexRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppMattersIndexRoute: AppMattersIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTrainingIndexRoute: AppTrainingIndexRoute,
  AppAdminStaffStaffIdRoute: AppAdminStaffStaffIdRoute,
  AppAdminStaffNewRoute: AppAdminStaffNewRoute,
  AppDocumentsTemplatesTemplateIdRoute: AppDocumentsTemplatesTemplateIdRoute,
  AppDocumentsTemplatesNewRoute: AppDocumentsTemplatesNewRoute,
  AppTrainingCoursesCourseIdRoute: AppTrainingCoursesCourseIdRoute,
  AppTrainingSchedulesScheduleIdRoute: AppTrainingSchedulesScheduleIdRoute,
  AppAdminServicesIndexRoute: AppAdminServicesIndexRoute,
  AppAdminStaffIndexRoute: AppAdminStaffIndexRoute,
  AppDocumentsTemplatesIndexRoute: AppDocumentsTemplatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PortalAppointmentsRoute: PortalAppointmentsRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalFinancialsRoute: PortalFinancialsRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalRegisterRoute: PortalRegisterRoute,
  StaffSetupPasswordRoute: StaffSetupPasswordRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalMattersMatterIdRoute: PortalMattersMatterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
