/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppMattersIndexRouteImport } from './routes/app/matters/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/app/documents/index'
import { Route as AppClientsIndexRouteImport } from './routes/app/clients/index'
import { Route as AppCalendarIndexRouteImport } from './routes/app/calendar/index'
import { Route as AppMattersNewRouteImport } from './routes/app/matters/new'
import { Route as AppMattersMatterIdRouteImport } from './routes/app/matters/$matterId'
import { Route as AppDocumentsUploadRouteImport } from './routes/app/documents/upload'
import { Route as AppClientsNewRouteImport } from './routes/app/clients/new'
import { Route as AppClientsClientIdRouteImport } from './routes/app/clients/$clientId'
import { Route as AppCalendarNewRouteImport } from './routes/app/calendar/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMattersIndexRoute = AppMattersIndexRouteImport.update({
  id: '/matters/',
  path: '/matters/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRoute,
} as any)
const AppMattersNewRoute = AppMattersNewRouteImport.update({
  id: '/matters/new',
  path: '/matters/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMattersMatterIdRoute = AppMattersMatterIdRouteImport.update({
  id: '/matters/$matterId',
  path: '/matters/$matterId',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsUploadRoute = AppDocumentsUploadRouteImport.update({
  id: '/documents/upload',
  path: '/documents/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarNewRoute = AppCalendarNewRouteImport.update({
  id: '/calendar/new',
  path: '/calendar/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/calendar/new': typeof AppCalendarNewRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/documents/upload': typeof AppDocumentsUploadRoute
  '/app/matters/$matterId': typeof AppMattersMatterIdRoute
  '/app/matters/new': typeof AppMattersNewRoute
  '/app/calendar': typeof AppCalendarIndexRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/matters': typeof AppMattersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/app/calendar/new': typeof AppCalendarNewRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/documents/upload': typeof AppDocumentsUploadRoute
  '/app/matters/$matterId': typeof AppMattersMatterIdRoute
  '/app/matters/new': typeof AppMattersNewRoute
  '/app/calendar': typeof AppCalendarIndexRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/matters': typeof AppMattersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/calendar/new': typeof AppCalendarNewRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/documents/upload': typeof AppDocumentsUploadRoute
  '/app/matters/$matterId': typeof AppMattersMatterIdRoute
  '/app/matters/new': typeof AppMattersNewRoute
  '/app/calendar/': typeof AppCalendarIndexRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/matters/': typeof AppMattersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/app/'
    | '/app/calendar/new'
    | '/app/clients/$clientId'
    | '/app/clients/new'
    | '/app/documents/upload'
    | '/app/matters/$matterId'
    | '/app/matters/new'
    | '/app/calendar'
    | '/app/clients'
    | '/app/documents'
    | '/app/matters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/app'
    | '/app/calendar/new'
    | '/app/clients/$clientId'
    | '/app/clients/new'
    | '/app/documents/upload'
    | '/app/matters/$matterId'
    | '/app/matters/new'
    | '/app/calendar'
    | '/app/clients'
    | '/app/documents'
    | '/app/matters'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/app/'
    | '/app/calendar/new'
    | '/app/clients/$clientId'
    | '/app/clients/new'
    | '/app/documents/upload'
    | '/app/matters/$matterId'
    | '/app/matters/new'
    | '/app/calendar/'
    | '/app/clients/'
    | '/app/documents/'
    | '/app/matters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matters/': {
      id: '/app/matters/'
      path: '/matters'
      fullPath: '/app/matters'
      preLoaderRoute: typeof AppMattersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar/': {
      id: '/app/calendar/'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matters/new': {
      id: '/app/matters/new'
      path: '/matters/new'
      fullPath: '/app/matters/new'
      preLoaderRoute: typeof AppMattersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matters/$matterId': {
      id: '/app/matters/$matterId'
      path: '/matters/$matterId'
      fullPath: '/app/matters/$matterId'
      preLoaderRoute: typeof AppMattersMatterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/upload': {
      id: '/app/documents/upload'
      path: '/documents/upload'
      fullPath: '/app/documents/upload'
      preLoaderRoute: typeof AppDocumentsUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/new': {
      id: '/app/clients/new'
      path: '/clients/new'
      fullPath: '/app/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/$clientId': {
      id: '/app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar/new': {
      id: '/app/calendar/new'
      path: '/calendar/new'
      fullPath: '/app/calendar/new'
      preLoaderRoute: typeof AppCalendarNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCalendarNewRoute: typeof AppCalendarNewRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppDocumentsUploadRoute: typeof AppDocumentsUploadRoute
  AppMattersMatterIdRoute: typeof AppMattersMatterIdRoute
  AppMattersNewRoute: typeof AppMattersNewRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppMattersIndexRoute: typeof AppMattersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCalendarNewRoute: AppCalendarNewRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppDocumentsUploadRoute: AppDocumentsUploadRoute,
  AppMattersMatterIdRoute: AppMattersMatterIdRoute,
  AppMattersNewRoute: AppMattersNewRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppMattersIndexRoute: AppMattersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
